/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
"use client";
import { useEffect, useState } from "react";

export default function SettingsPage() {
  const [settings, setSettings] = useState<Record<string,string>>({});
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    // settings API は未実装のため、ローカルstateで管理
    setSettings({
      site_name: "AI活用ラボ",
      site_description: "最新AIツールの使い方・活用事例・副業情報を毎日お届け",
      articles_per_day: "3",
      auto_publish: "true",
      target_pv: "100000",
      adsense_id: "",
    });
    setLoading(false);
  }, []);

  function handleSave() {
    setSaving(true);
    setTimeout(() => { setSaving(false); setSaved(true); setTimeout(() => setSaved(false), 2000); }, 500);
  }

  const fields = [
    { key:"site_name", label:"サイト名", type:"text" },
    { key:"site_description", label:"サイト説明", type:"text" },
    { key:"articles_per_day", label:"1日の目標記事生成数", type:"number" },
    { key:"target_pv", label:"目標月間PV", type:"number" },
    { key:"adsense_id", label:"Google AdSense Publisher ID", type:"text", placeholder:"ca-pub-XXXXXXXXXX" },
  ];

  if (loading) return <div className="animate-pulse space-y-4"><div className="h-8 bg-gray-200 rounded w-32" /><div className="h-64 bg-gray-200 rounded" /></div>;

  return (
    <div className="max-w-2xl space-y-5">
      <h1 className="text-2xl font-bold text-gray-900">⚙️ 設定</h1>

      <div className="bg-white rounded-xl border border-gray-100 p-5 space-y-5">
        <h2 className="font-semibold text-gray-800">サイト基本設定</h2>
        {fields.map((f: any) => (
          <div key={f.key}>
            <label className="block text-sm font-medium text-gray-700 mb-1">{f.label}</label>
            <input type={f.type} value={settings[f.key]||""} placeholder={f.placeholder}
              onChange={e => setSettings(s => ({...s, [f.key]: e.target.value}))}
              className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none" />
          </div>
        ))}
        <div className="flex items-center gap-3">
          <input type="checkbox" id="auto_publish" checked={settings.auto_publish === "true"}
            onChange={e => setSettings(s => ({...s, auto_publish: e.target.checked ? "true" : "false"}))}
            className="rounded text-purple-600" />
          <label htmlFor="auto_publish" className="text-sm text-gray-700">AI生成後に自動公開する</label>
        </div>
        <button onClick={handleSave} disabled={saving}
          className="w-full bg-purple-600 hover:bg-purple-700 disabled:opacity-40 text-white py-2.5 rounded-lg text-sm font-medium">
          {saved ? "✅ 保存しました" : saving ? "保存中..." : "設定を保存する"}
        </button>
      </div>

      <div className="bg-amber-50 rounded-xl border border-amber-200 p-5 space-y-3">
        <h2 className="font-semibold text-amber-800">🔑 APIキー設定</h2>
        <p className="text-sm text-amber-700">AI記事生成には ANTHROPIC_API_KEY が必要です。プロジェクトの <code className="bg-amber-100 px-1 rounded">.env</code> ファイルに設定してください。</p>
        <div className="bg-amber-100 rounded-lg p-3 font-mono text-xs text-amber-800">
          ANTHROPIC_API_KEY=sk-ant-api03-...
        </div>
        <a href="https://console.anthropic.com" target="_blank" rel="noopener noreferrer" className="text-amber-700 hover:underline text-sm">Anthropic Console でAPIキーを取得する →</a>
      </div>

      <div className="bg-white rounded-xl border border-gray-100 p-5 space-y-3">
        <h2 className="font-semibold text-gray-800">📋 SEO設定ガイド</h2>
        <div className="space-y-2 text-sm text-gray-600">
          <p>✅ <strong>Google Search Console</strong> にサイトを登録してURL検証を行う</p>
          <p>✅ <strong>サイトマップ</strong>（/sitemap.xml）を Search Console に送信する</p>
          <p>✅ <strong>Google Analytics 4</strong> を設定してリアルタイムPVを計測する</p>
          <p>✅ <strong>Google AdSense</strong> の審査申請（月間1,000PV以上を目安に）</p>
        </div>
      </div>
    </div>
  );
}
