/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
"use client";
import { useEffect, useState } from "react";
import { LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";
import Link from "next/link";

export default function AnalyticsPage() {
  const [data, setData] = useState<any>(null);
  const [days, setDays] = useState(30);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    fetch(`/api/analytics?days=${days}`).then(r => r.json()).then(d => { setData(d); setLoading(false); });
  }, [days]);

  const pvData = (data?.viewsByDay ?? []).map((r: any) => ({ date: String(r.date).slice(5), PV: Number(r.count) }));
  const ov = data?.overview ?? {};

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-gray-900">📈 アナリティクス</h1>
        <div className="flex gap-2">
          {[7, 30, 90].map(d => (
            <button key={d} onClick={() => setDays(d)}
              className={`px-3 py-1.5 text-sm rounded-lg font-medium ${days === d ? "bg-purple-600 text-white" : "bg-white border border-gray-200 text-gray-600 hover:border-purple-400"}`}>
              {d}日
            </button>
          ))}
        </div>
      </div>

      {/* KPIs */}
      <div className="grid grid-cols-4 gap-4">
        {[
          { label:"総PV", value:(ov.totalViews||0).toLocaleString(), color:"text-purple-600" },
          { label:"本日PV", value:(ov.todayViews||0).toLocaleString(), color:"text-indigo-600" },
          { label:"月間PV推計", value:(ov.projectedMonthlyPV||0).toLocaleString(), color:"text-sky-600" },
          { label:"公開記事数", value:(ov.publishedArticles||0).toLocaleString(), color:"text-gray-900" },
        ].map(card => (
          <div key={card.label} className="bg-white rounded-xl border border-gray-100 p-5">
            <p className="text-xs text-gray-500 font-medium uppercase">{card.label}</p>
            <p className={`text-3xl font-bold mt-1 ${card.color}`}>{card.value}</p>
          </div>
        ))}
      </div>

      {/* PV推移 */}
      <div className="bg-white rounded-xl border border-gray-100 p-5">
        <h2 className="font-semibold text-gray-800 mb-4">PV推移（直近{days}日）</h2>
        {loading ? <div className="h-56 bg-gray-100 rounded animate-pulse" /> :
        pvData.length > 0 ? (
          <ResponsiveContainer width="100%" height={220}>
            <LineChart data={pvData}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
              <XAxis dataKey="date" tick={{ fontSize: 11 }} />
              <YAxis tick={{ fontSize: 11 }} />
              <Tooltip />
              <Line type="monotone" dataKey="PV" stroke="#8b5cf6" strokeWidth={2.5} dot={false} />
            </LineChart>
          </ResponsiveContainer>
        ) : <div className="h-56 flex items-center justify-center text-gray-400 text-sm">データが溜まると自動で表示されます</div>}
      </div>

      {/* 10万PV戦略ロードマップ */}
      <div className="bg-white rounded-xl border border-gray-100 p-5">
        <h2 className="font-semibold text-gray-800 mb-4">🗺 月間10万PV達成ロードマップ</h2>
        <div className="space-y-4">
          {[
            { phase:"Phase 1（1〜2ヶ月）", goal:"月間5,000 PV", actions:["週3〜5記事をAI生成・公開","ロングテールキーワード20〜50件を攻略","内部リンク構造を整備","GoogleサーチコンソールでURL登録"], color:"bg-blue-50 border-blue-200" },
            { phase:"Phase 2（3〜6ヶ月）", goal:"月間3万 PV", actions:["毎日1記事のペースに加速","SNS投稿と連動してPVを底上げ","人気カテゴリを深掘りしてクラスター構築","アフィリエイト収益化を開始"], color:"bg-purple-50 border-purple-200" },
            { phase:"Phase 3（7〜12ヶ月）", goal:"月間10万+ PV", actions:["AI生成×人間編集でコンテンツを月50〜100本","被リンク獲得・AO対策強化","広告案件・スポンサード記事を開始","YouTube・ニュースレターと連動"], color:"bg-emerald-50 border-emerald-200" },
          ].map(step => (
            <div key={step.phase} className={`border rounded-xl p-4 ${step.color}`}>
              <div className="flex items-center justify-between mb-2">
                <h3 className="font-semibold text-gray-800 text-sm">{step.phase}</h3>
                <span className="text-xs font-bold text-purple-600 bg-purple-100 px-2 py-0.5 rounded-full">{step.goal}</span>
              </div>
              <ul className="space-y-1">
                {step.actions.map((a, i) => <li key={i} className="text-xs text-gray-600 flex items-start gap-1.5"><span className="text-purple-400 mt-0.5">•</span>{a}</li>)}
              </ul>
            </div>
          ))}
        </div>
      </div>

      {/* 人気記事 */}
      <div className="bg-white rounded-xl border border-gray-100 p-5">
        <div className="flex items-center justify-between mb-4">
          <h2 className="font-semibold text-gray-800">人気記事 TOP10</h2>
          <Link href="/admin/articles" className="text-purple-600 text-sm hover:underline">すべて →</Link>
        </div>
        {(data?.topArticles ?? []).length === 0 ? (
          <p className="text-gray-400 text-sm text-center py-8">記事を公開するとランキングが表示されます</p>
        ) : (
          <div className="space-y-2">
            {(data?.topArticles ?? []).map((article: any, i: number) => (
              <div key={article.id} className="flex items-center gap-3 py-2 border-b border-gray-50 last:border-0">
                <span className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold ${i < 3 ? "bg-purple-100 text-purple-700" : "bg-gray-100 text-gray-500"}`}>{i+1}</span>
                <div className="flex-1 min-w-0">
                  <Link href={`/admin/articles/${article.id}`} className="text-sm text-gray-800 hover:text-purple-600 font-medium truncate block">{article.title}</Link>
                </div>
                <span className="text-sm font-semibold text-gray-700">{(article._count?.views||0).toLocaleString()} PV</span>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
