/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
"use client";
import { useEffect, useState } from "react";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";

const TYPE_LABEL: Record<string, string> = { adsense:"AdSense", affiliate:"アフィリエイト", sponsored:"スポンサード", inquiry:"問い合わせ" };
const TYPE_COLOR: Record<string, string> = { adsense:"bg-purple-100 text-purple-700", affiliate:"bg-emerald-100 text-emerald-700", sponsored:"bg-amber-100 text-amber-700", inquiry:"bg-sky-100 text-sky-700" };

export default function RevenuePage() {
  const [revenues, setRevenues] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ type:"adsense", amount:"", note:"" });
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    fetch("/api/revenue").then(r => r.json()).then(d => { setRevenues(d); setLoading(false); });
  }, []);

  async function handleAdd() {
    setSaving(true);
    const res = await fetch("/api/revenue", { method:"POST", headers:{"Content-Type":"application/json"}, body: JSON.stringify({...form, amount: Number(form.amount)}) });
    const r = await res.json();
    setRevenues(prev => [r, ...prev]);
    setShowForm(false);
    setForm({ type:"adsense", amount:"", note:"" });
    setSaving(false);
  }

  const total = revenues.reduce((s, r) => s + r.amount, 0);
  const byType = revenues.reduce((acc: Record<string,number>, r) => { acc[r.type] = (acc[r.type]||0) + r.amount; return acc; }, {});
  const barData = Object.entries(byType).map(([type, total]) => ({ type: TYPE_LABEL[type]||type, total: Math.round(total as number) }));

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">💴 収益管理</h1>
          <p className="text-sm text-gray-500">累計: <strong className="text-emerald-600">¥{Math.round(total).toLocaleString()}</strong></p>
        </div>
        <button onClick={() => setShowForm(s=>!s)} className="bg-purple-600 hover:bg-purple-700 text-white text-sm px-4 py-2 rounded-lg font-medium">
          + 収益記録
        </button>
      </div>

      {showForm && (
        <div className="bg-white rounded-xl border border-gray-100 p-5 space-y-4">
          <h2 className="font-semibold text-gray-800">収益を記録する</h2>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">種別</label>
              <select value={form.type} onChange={e=>setForm(f=>({...f,type:e.target.value}))} className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none">
                <option value="adsense">Google AdSense</option>
                <option value="affiliate">アフィリエイト</option>
                <option value="sponsored">スポンサード記事</option>
                <option value="inquiry">お問い合わせ案件</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">金額 (円)</label>
              <input type="number" value={form.amount} onChange={e=>setForm(f=>({...f,amount:e.target.value}))} className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none" placeholder="5000" />
            </div>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">メモ</label>
            <input value={form.note} onChange={e=>setForm(f=>({...f,note:e.target.value}))} className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none" />
          </div>
          <div className="flex gap-3">
            <button onClick={() => setShowForm(false)} className="flex-1 border border-gray-300 text-gray-600 py-2 rounded-lg text-sm">キャンセル</button>
            <button onClick={handleAdd} disabled={saving||!form.amount} className="flex-1 bg-purple-600 hover:bg-purple-700 disabled:opacity-40 text-white py-2 rounded-lg text-sm font-medium">{saving?"保存中...":"記録する"}</button>
          </div>
        </div>
      )}

      {barData.length > 0 && (
        <div className="bg-white rounded-xl border border-gray-100 p-5">
          <h2 className="font-semibold text-gray-800 mb-4">収益内訳</h2>
          <ResponsiveContainer width="100%" height={200}>
            <BarChart data={barData}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
              <XAxis dataKey="type" tick={{ fontSize: 12 }} />
              <YAxis tickFormatter={v => `¥${v.toLocaleString()}`} tick={{ fontSize: 11 }} />
              <Tooltip formatter={(v: any) => [`¥${Number(v).toLocaleString()}`, "収益"]} />
              <Bar dataKey="total" fill="#8b5cf6" radius={[4,4,0,0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      )}

      <div className="bg-white rounded-xl border border-gray-100 overflow-hidden">
        <table className="w-full">
          <thead className="bg-gray-50 border-b border-gray-100">
            <tr>
              <th className="text-left text-xs font-semibold text-gray-500 px-4 py-3">種別</th>
              <th className="text-right text-xs font-semibold text-gray-500 px-4 py-3">金額</th>
              <th className="text-left text-xs font-semibold text-gray-500 px-4 py-3">メモ</th>
              <th className="text-left text-xs font-semibold text-gray-500 px-4 py-3 w-28">日付</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-50">
            {loading ? (
              <tr><td colSpan={4} className="text-center text-gray-400 py-8">読み込み中...</td></tr>
            ) : revenues.map((r: any) => (
              <tr key={r.id} className="hover:bg-gray-50">
                <td className="px-4 py-3">
                  <span className={`text-xs px-2 py-1 rounded-full font-medium ${TYPE_COLOR[r.type]||"bg-gray-100 text-gray-600"}`}>{TYPE_LABEL[r.type]||r.type}</span>
                </td>
                <td className="px-4 py-3 text-right font-semibold text-emerald-600">¥{Math.round(r.amount).toLocaleString()}</td>
                <td className="px-4 py-3 text-sm text-gray-500">{r.note||"—"}</td>
                <td className="px-4 py-3 text-xs text-gray-400">{new Date(r.date).toLocaleDateString("ja-JP")}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
