/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * ----------------------------------------------------------------*/
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { z } from "zod";
import { slugify, estimateReadingTime } from "@/lib/utils";

const ArticleSchema = z.object({
  title: z.string().min(1),
  excerpt: z.string().min(1),
  content: z.string().min(1),
  categoryId: z.string().optional(),
  status: z.enum(["draft", "published", "scheduled"]).default("draft"),
  seoTitle: z.string().optional(),
  seoDescription: z.string().optional(),
  seoKeywords: z.string().optional(),
  scheduledAt: z.string().optional(),
});

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const status = searchParams.get("status");
    const categorySlug = searchParams.get("category");
    const page = parseInt(searchParams.get("page") || "1");
    const limit = parseInt(searchParams.get("limit") || "20");
    const skip = (page - 1) * limit;

    const q = searchParams.get("q");

    const where: any = {};
    if (status) where.status = status;
    if (categorySlug) where.category = { slug: categorySlug };
    if (q) {
      where.OR = [
        { title: { contains: q } },
        { excerpt: { contains: q } },
        { seoKeywords: { contains: q } },
      ];
    }

    const [articles, total] = await Promise.all([
      prisma.article.findMany({
        where,
        include: { category: true, tags: { include: { tag: true } }, _count: { select: { views: true } } },
        orderBy: { createdAt: "desc" },
        skip,
        take: limit,
      }),
      prisma.article.count({ where }),
    ]);

    return NextResponse.json({ articles, total, page, pages: Math.ceil(total / limit) });
  } catch (e) {
    return NextResponse.json({ error: "取得失敗" }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const data = ArticleSchema.parse(body);
    const slug = slugify(data.title) + "-" + Date.now().toString(36);
    const wordCount = data.content.split(/\s+/).length;
    const readingTime = estimateReadingTime(data.content);

    const article = await prisma.article.create({
      data: {
        ...data,
        slug,
        wordCount,
        readingTime,
        publishedAt: data.status === "published" ? new Date() : null,
        scheduledAt: data.scheduledAt ? new Date(data.scheduledAt) : null,
        aiGenerated: false,
      },
    });
    return NextResponse.json(article, { status: 201 });
  } catch (e: any) {
    return NextResponse.json({ error: e.message || "作成失敗" }, { status: 400 });
  }
}
