/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";

export default function ArticleEditPage({ params }: { params: Promise<{ id: string }> }) {
  const router = useRouter();
  const [article, setArticle] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState<any>({});
  const [id, setId] = useState("");

  useEffect(() => {
    params.then(p => {
      setId(p.id);
      fetch(`/api/articles/${p.id}`).then(r => r.json()).then(a => {
        setArticle(a);
        setForm({ title: a.title, excerpt: a.excerpt || "", content: a.content, status: a.status, seoTitle: a.seoTitle || "", seoDescription: a.seoDescription || "", seoKeywords: a.seoKeywords || "" });
        setLoading(false);
      });
    });
  }, []);

  async function handleSave() {
    setSaving(true);
    await fetch(`/api/articles/${id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(form),
    });
    setSaving(false);
    alert("保存しました");
  }

  async function handleDelete() {
    if (!confirm("この記事を削除しますか？")) return;
    await fetch(`/api/articles/${id}`, { method: "DELETE" });
    router.push("/admin/articles");
  }

  if (loading) return <div className="animate-pulse space-y-4"><div className="h-8 bg-gray-200 rounded w-64" /><div className="h-96 bg-gray-200 rounded" /></div>;

  return (
    <div className="max-w-4xl space-y-5">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Link href="/admin/articles" className="text-gray-400 hover:text-gray-600 text-sm">← 記事一覧</Link>
          <h1 className="text-xl font-bold text-gray-900">記事編集</h1>
          {article?.aiGenerated && <span className="text-xs bg-purple-100 text-purple-600 px-2 py-0.5 rounded-full">AI生成</span>}
        </div>
        <div className="flex gap-3">
          {article?.status === "published" && (
            <Link href={`/articles/${article.slug}`} target="_blank" className="border border-gray-200 text-gray-600 text-sm px-3 py-1.5 rounded-lg">
              公開ページ →
            </Link>
          )}
          <button onClick={handleDelete} className="border border-red-200 text-red-500 text-sm px-3 py-1.5 rounded-lg hover:bg-red-50">削除</button>
          <button onClick={handleSave} disabled={saving} className="bg-purple-600 hover:bg-purple-700 text-white text-sm px-4 py-1.5 rounded-lg disabled:opacity-50">
            {saving ? "保存中..." : "保存する"}
          </button>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-5">
        <div className="col-span-2 space-y-4">
          <div className="bg-white rounded-xl border border-gray-100 p-5 space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">タイトル</label>
              <input value={form.title || ""} onChange={e => setForm((f: any) => ({...f, title: e.target.value}))}
                className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none" />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">要約</label>
              <textarea value={form.excerpt || ""} onChange={e => setForm((f: any) => ({...f, excerpt: e.target.value}))}
                rows={2} className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none resize-none" />
            </div>
            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="block text-sm font-medium text-gray-700">本文</label>
                <span className="text-xs text-gray-400">{(form.content || "").split(/\S+/).length - 1} 文字</span>
              </div>
              <textarea value={form.content || ""} onChange={e => setForm((f: any) => ({...f, content: e.target.value}))}
                rows={24} className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none resize-y font-mono" />
            </div>
          </div>
          <div className="bg-white rounded-xl border border-gray-100 p-5 space-y-4">
            <h2 className="font-semibold text-gray-800">🔍 SEO設定</h2>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">SEOタイトル</label>
              <input value={form.seoTitle || ""} onChange={e => setForm((f: any) => ({...f, seoTitle: e.target.value}))}
                className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none" />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">メタディスクリプション</label>
              <textarea value={form.seoDescription || ""} onChange={e => setForm((f: any) => ({...f, seoDescription: e.target.value}))}
                rows={2} className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none resize-none" />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">キーワード</label>
              <input value={form.seoKeywords || ""} onChange={e => setForm((f: any) => ({...f, seoKeywords: e.target.value}))}
                className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none" />
            </div>
          </div>
        </div>
        <div className="space-y-4">
          <div className="bg-white rounded-xl border border-gray-100 p-4">
            <h3 className="font-semibold text-gray-800 mb-3 text-sm">記事情報</h3>
            <div className="space-y-2 text-xs text-gray-500">
              <div className="flex justify-between"><span>作成日</span><span>{new Date(article.createdAt).toLocaleDateString("ja-JP")}</span></div>
              <div className="flex justify-between"><span>PV数</span><span className="font-semibold text-gray-800">{(article._count?.views ?? 0).toLocaleString()}</span></div>
              <div className="flex justify-between"><span>文字数</span><span>{article.wordCount?.toLocaleString()}</span></div>
              <div className="flex justify-between"><span>読了時間</span><span>約{article.readingTime}分</span></div>
            </div>
          </div>
          <div className="bg-white rounded-xl border border-gray-100 p-4">
            <h3 className="font-semibold text-gray-800 mb-3 text-sm">公開設定</h3>
            {["draft","published","scheduled"].map((s: any) => (
              <label key={s} className="flex items-center gap-2 cursor-pointer mb-2">
                <input type="radio" name="status" value={s} checked={form.status === s}
                  onChange={() => setForm((f: any) => ({...f, status: s}))} />
                <span className="text-sm">{({ draft:"下書き", published:"公開中", scheduled:"予約公開" } as Record<string,string>)[s]}</span>
              </label>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
