/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * ----------------------------------------------------------------*/
"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { signOut } from "next-auth/react";

const navItems = [
  { href: "/admin/dashboard", icon: "📊", label: "ダッシュボード" },
  { href: "/admin/articles", icon: "📝", label: "記事管理" },
  { href: "/admin/generate", icon: "🤖", label: "AI記事生成" },
  { href: "/admin/keywords", icon: "🔍", label: "キーワード管理" },
  { href: "/admin/analytics", icon: "📈", label: "アナリティクス" },
  { href: "/admin/affiliates", icon: "💰", label: "アフィリエイト" },
  { href: "/admin/revenue", icon: "💴", label: "収益管理" },
  { href: "/admin/settings", icon: "⚙️", label: "設定" },
];

export default function AdminLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();

  return (
    <div className="flex min-h-screen bg-gray-50">
      {/* Sidebar */}
      <aside className="fixed top-0 left-0 h-screen w-60 bg-gray-900 text-white flex flex-col z-50">
        <div className="p-5 border-b border-gray-700">
          <Link href="/admin/dashboard" className="flex items-center gap-2">
            <span className="text-2xl">🤖</span>
            <div>
              <div className="font-bold text-sm">AI活用ラボ</div>
              <div className="text-gray-400 text-xs">管理システム</div>
            </div>
          </Link>
        </div>
        <nav className="flex-1 p-3 space-y-1 overflow-y-auto">
          {navItems.map(item => (
            <Link
              key={item.href}
              href={item.href}
              className={`flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm transition-colors ${
                pathname === item.href || pathname.startsWith(item.href + "/")
                  ? "bg-purple-600 text-white"
                  : "text-gray-300 hover:bg-gray-800"
              }`}
            >
              <span>{item.icon}</span>
              <span>{item.label}</span>
            </Link>
          ))}
        </nav>
        <div className="p-3 border-t border-gray-700">
          <Link href="/" target="_blank" className="flex items-center gap-3 px-3 py-2 rounded-lg text-sm text-gray-300 hover:bg-gray-800 mb-1">
            <span>🌐</span><span>公開サイトを見る</span>
          </Link>
          <button
            onClick={() => signOut({ callbackUrl: "/login" })}
            className="w-full flex items-center gap-3 px-3 py-2 rounded-lg text-sm text-gray-300 hover:bg-gray-800"
          >
            <span>🚪</span><span>ログアウト</span>
          </button>
        </div>
      </aside>
      {/* Main */}
      <main className="ml-60 flex-1 p-8 min-h-screen">
        {children}
      </main>
    </div>
  );
}
