/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

const PRIORITY_COLOR: Record<string, string> = {
  high: "bg-red-100 text-red-700",
  medium: "bg-yellow-100 text-yellow-700",
  low: "bg-gray-100 text-gray-600",
};
const PRIORITY_LABEL: Record<string, string> = { high:"高優先", medium:"中優先", low:"低優先" };
const STATUS_LABEL: Record<string, string> = { pending:"未着手", in_progress:"作成中", published:"公開済み" };

export default function KeywordsPage() {
  const [keywords, setKeywords] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState("all");

  async function load(status?: string) {
    setLoading(true);
    const q = status && status !== "all" ? `?status=${status}` : "";
    const d = await fetch(`/api/keywords${q}`).then(r => r.json());
    setKeywords(d);
    setLoading(false);
  }

  useEffect(() => { load(); }, []);

  async function deleteKw(id: string) {
    if (!confirm("削除しますか？")) return;
    await fetch(`/api/keywords/${id}`, { method: "DELETE" });
    setKeywords(prev => prev.filter(k => k.id !== id));
  }

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">キーワード管理</h1>
          <p className="text-sm text-gray-500">{keywords.length}件のキーワード</p>
        </div>
        <Link href="/admin/keywords/new" className="bg-purple-600 hover:bg-purple-700 text-white text-sm px-4 py-2 rounded-lg font-medium">
          + キーワード追加
        </Link>
      </div>

      <div className="flex gap-2">
        {["all","pending","published"].map((f: any) => (
          <button key={f} onClick={() => { setFilter(f); load(f === "all" ? undefined : f); }}
            className={`px-4 py-1.5 rounded-full text-sm font-medium transition-colors ${filter === f ? "bg-purple-600 text-white" : "bg-white border border-gray-200 text-gray-600 hover:border-purple-400"}`}>
            {({ all:"すべて", pending:"未着手", published:"公開済み" } as Record<string,string>)[f]}
          </button>
        ))}
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        {loading ? <div className="p-8 text-center text-gray-400">読み込み中...</div> :
        keywords.length === 0 ? (
          <div className="p-12 text-center">
            <p className="text-gray-400 mb-3">キーワードがありません</p>
            <Link href="/admin/keywords/new" className="text-purple-600 hover:underline text-sm">キーワードを追加する →</Link>
          </div>
        ) : (
          <table className="w-full">
            <thead className="bg-gray-50 border-b border-gray-100">
              <tr>
                <th className="text-left text-xs font-semibold text-gray-500 px-4 py-3">キーワード</th>
                <th className="text-right text-xs font-semibold text-gray-500 px-4 py-3 w-28">月間検索数</th>
                <th className="text-center text-xs font-semibold text-gray-500 px-4 py-3 w-20">難易度</th>
                <th className="text-center text-xs font-semibold text-gray-500 px-4 py-3 w-20">優先度</th>
                <th className="text-center text-xs font-semibold text-gray-500 px-4 py-3 w-20">ステータス</th>
                <th className="text-right text-xs font-semibold text-gray-500 px-4 py-3 w-32">操作</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {keywords.map((kw: any) => (
                <tr key={kw.id} className="hover:bg-gray-50">
                  <td className="px-4 py-3">
                    <p className="text-sm font-medium text-gray-800">{kw.keyword}</p>
                    {kw.category && <p className="text-xs text-gray-400">{kw.category}</p>}
                  </td>
                  <td className="px-4 py-3 text-right">
                    <span className="text-sm font-semibold text-gray-800">{kw.searchVolume.toLocaleString()}</span>
                  </td>
                  <td className="px-4 py-3 text-center">
                    <span className={`text-sm font-bold ${kw.difficulty < 40 ? "text-emerald-600" : kw.difficulty < 60 ? "text-yellow-600" : "text-red-600"}`}>
                      {kw.difficulty}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-center">
                    <span className={`text-xs px-2 py-1 rounded-full font-medium ${PRIORITY_COLOR[kw.priority]}`}>{PRIORITY_LABEL[kw.priority]}</span>
                  </td>
                  <td className="px-4 py-3 text-center">
                    <span className="text-xs text-gray-500">{STATUS_LABEL[kw.status] ?? kw.status}</span>
                  </td>
                  <td className="px-4 py-3 text-right">
                    <div className="flex items-center justify-end gap-2">
                      <Link href={`/admin/generate?kw=${kw.id}`}
                        className="text-xs px-2 py-1 rounded border border-purple-200 text-purple-600 hover:bg-purple-50">
                        AI生成
                      </Link>
                      <button onClick={() => deleteKw(kw.id)} className="text-xs px-2 py-1 rounded border border-red-200 text-red-500 hover:bg-red-50">削除</button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
