/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
import Link from "next/link";

const categories = [
  { slug:"chatgpt", name:"ChatGPT活用術" },
  { slug:"ai-business", name:"AI業務効率化" },
  { slug:"ai-tools", name:"AIツール比較" },
  { slug:"prompt", name:"プロンプト技術" },
  { slug:"ai-income", name:"AI副業・収益化" },
  { slug:"ai-news", name:"AI最新ニュース" },
];

export default function MediaLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <header className="border-b border-gray-100 sticky top-0 bg-white/95 backdrop-blur z-40">
        <div className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <span className="text-xl">🤖</span>
            <span className="font-bold text-gray-900">AI活用ラボ</span>
          </Link>
          <nav className="hidden md:flex items-center gap-1">
            {categories.slice(0,4).map((c: any) => (
              <Link key={c.slug} href={`/category/${c.slug}`} className="text-sm text-gray-600 hover:text-purple-600 px-3 py-1.5 rounded-md hover:bg-purple-50 transition-colors">
                {c.name}
              </Link>
            ))}
          </nav>
          <div className="flex items-center gap-2">
            <Link href="/search" className="text-sm text-gray-500 hover:text-purple-600 px-2 py-1.5 rounded-md hover:bg-purple-50 transition-colors" aria-label="記事を検索">🔍</Link>
            <Link href="/admin/dashboard" className="text-xs bg-purple-600 text-white px-3 py-1.5 rounded-lg hover:bg-purple-700">管理画面</Link>
          </div>
        </div>
      </header>
      {children}
      {/* Footer */}
      <footer className="bg-gray-900 text-gray-400 mt-16">
        <div className="max-w-6xl mx-auto px-4 py-10">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 mb-8">
            <div>
              <div className="text-white font-bold mb-3 flex items-center gap-2"><span>🤖</span>AI活用ラボ</div>
              <p className="text-xs leading-relaxed">最新AIツールの使い方・活用事例・副業情報を毎日お届けするメディアです。</p>
            </div>
            <div>
              <h3 className="text-white font-semibold mb-3 text-sm">カテゴリ</h3>
              <ul className="space-y-1">
                {categories.map((c: any) => (
                  <li key={c.slug}><Link href={`/category/${c.slug}`} className="text-xs hover:text-white transition-colors">{c.name}</Link></li>
                ))}
              </ul>
            </div>
            <div>
              <h3 className="text-white font-semibold mb-3 text-sm">人気コンテンツ</h3>
              <ul className="space-y-1">
                <li><Link href="/articles" className="text-xs hover:text-white">すべての記事</Link></li>
                <li><Link href="/category/chatgpt" className="text-xs hover:text-white">ChatGPT使い方</Link></li>
                <li><Link href="/category/prompt" className="text-xs hover:text-white">プロンプト集</Link></li>
              </ul>
            </div>
            <div>
              <h3 className="text-white font-semibold mb-3 text-sm">情報</h3>
              <ul className="space-y-1">
                <li><span className="text-xs">お問い合わせ: contact@ai-media.jp</span></li>
              </ul>
            </div>
          </div>
          <div className="border-t border-gray-800 pt-6 text-center text-xs">
            © 2026 AI活用ラボ. All rights reserved.
          </div>
        </div>
      </footer>
    </div>
  );
}
