/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI v2056.8
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * Redistribution / derivative-work / reverse-engineering prohibited
 * (著作権法 / 不正競争防止法 / 当社利用規約 第 8 条).
 * License inquiries: nomura.y@soloptilink.com
 * ----------------------------------------------------------------*/
import Link from "next/link";
import SiteHeader, { Wordmark } from "@/components/media/SiteHeader";
import { CATEGORIES, OPERATOR } from "@/lib/media";

function todayLabel() {
  const d = new Date(new Date().toLocaleString("en-US", { timeZone: "Asia/Tokyo" }));
  const w = ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"][d.getDay()];
  return `${d.getFullYear()}.${String(d.getMonth() + 1).padStart(2, "0")}.${String(d.getDate()).padStart(2, "0")} ${w}`;
}

export default function MediaLayout({ children }: { children: React.ReactNode }) {
  const cats = CATEGORIES.map(({ slug, name }) => ({ slug, name }));
  return (
    <div className="min-h-screen">
      <a href="#main" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-50 focus:bg-ink focus:px-4 focus:py-2 focus:text-white">
        本文へ移動
      </a>
      <SiteHeader categories={cats} today={todayLabel()} />
      <div id="main" tabIndex={-1} className="outline-none">{children}</div>

      <footer className="mt-24 bg-ink text-white/70">
        <div className="mx-auto max-w-[1240px] px-5 pt-16 pb-10 md:px-6">
          <div className="grid gap-12 md:grid-cols-[1.4fr_1fr_1fr]">
            <div>
              <Link href="/" aria-label="AI活用ラボ トップへ">
                <Wordmark invert />
              </Link>
              <p className="mt-5 max-w-sm text-[13px] leading-[1.9]">
                ChatGPT・Claude・Geminiをはじめとする生成AIを、仕事の現場でどう使うか。使い方・比較・事例を、実務の目線で整理して届けるメディアです。
              </p>
            </div>
            <div>
              <p className="kicker mb-4 text-white/60">Categories</p>
              <ul className="space-y-2.5 text-[13px]">
                {CATEGORIES.map((c) => (
                  <li key={c.slug}>
                    <Link href={`/category/${c.slug}`} className="hover:text-white">{c.name}</Link>
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <p className="kicker mb-4 text-white/60">About</p>
              <ul className="space-y-2.5 text-[13px]">
                <li><Link href="/articles" className="hover:text-white">すべての記事</Link></li>
                <li><Link href="/search" className="hover:text-white">記事を検索</Link></li>
                <li><Link href="/feed" className="hover:text-white">RSSフィード</Link></li>
                <li><Link href="/sitemap.xml" className="hover:text-white">サイトマップ</Link></li>
                <li><a href={OPERATOR.url} target="_blank" rel="noopener" className="hover:text-white">運営会社</a></li>
                <li><a href={`mailto:${OPERATOR.email}`} className="hover:text-white">お問い合わせ</a></li>
              </ul>
            </div>
          </div>
          <div className="mt-14 flex flex-col gap-3 border-t border-white/10 pt-6 text-[11.5px] text-white/60 md:flex-row md:items-center md:justify-between">
            <p>運営：{OPERATOR.name}（{OPERATOR.summary}）</p>
            <p className="font-[family-name:var(--font-latin)] tracking-wider">© {new Date().getFullYear()} AI Katsuyo Lab</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
