/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
export default function HomeLoading() {
  return (
    <div className="min-h-screen">
      {/* ヒーローセクション */}
      <section className="bg-gradient-to-br from-purple-900 via-purple-800 to-indigo-900 py-16 px-4">
        <div className="max-w-4xl mx-auto text-center space-y-4">
          <div className="h-12 w-80 bg-white/20 rounded-xl animate-pulse mx-auto" />
          <div className="h-6 w-64 bg-white/20 rounded animate-pulse mx-auto" />
          <div className="h-12 w-full max-w-xl bg-white/20 rounded-xl animate-pulse mx-auto" />
        </div>
      </section>

      <main className="max-w-6xl mx-auto px-4 py-10 space-y-12">
        {/* 新着記事 */}
        <section>
          <div className="h-7 w-32 bg-gray-200 rounded animate-pulse mb-6" />
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {Array.from({ length: 6 }).map((_, i) => (
              <div key={i} className="bg-white rounded-xl border border-gray-100 overflow-hidden">
                <div className="h-40 bg-gradient-to-br from-purple-100 to-indigo-100 animate-pulse" />
                <div className="p-4 space-y-2">
                  <div className="h-3 w-16 bg-purple-100 rounded-full animate-pulse" />
                  <div className="h-4 w-full bg-gray-200 rounded animate-pulse" />
                  <div className="h-4 w-3/4 bg-gray-200 rounded animate-pulse" />
                  <div className="h-3 w-full bg-gray-100 rounded animate-pulse" />
                </div>
              </div>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
