/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI v2056.8
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * Redistribution / derivative-work / reverse-engineering prohibited
 * (著作権法 / 不正競争防止法 / 当社利用規約 第 8 条).
 * License inquiries: nomura.y@soloptilink.com
 * ----------------------------------------------------------------*/
import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
import { prisma } from "@/lib/prisma";
import ArticleCard, { SectionHeading, type CardArticle } from "@/components/media/ArticleCard";
import { CATEGORIES, OPERATOR, SITE_NAME, SITE_URL, categoryCover, categoryMeta, hasHero, heroCover } from "@/lib/media";

export const revalidate = 300;

export const metadata: Metadata = {
  title: { absolute: "AI活用ラボ | ChatGPT・Claude・Geminiの使い方・業務効率化・AI副業" },
  description: "ChatGPT・Claude・Geminiなど生成AIの使い方、業務効率化の事例、ツール比較、AI副業まで。仕事で使えるAIの情報を実務の目線で整理して届けるメディアです。",
  alternates: { canonical: SITE_URL },
  openGraph: {
    title: "AI活用ラボ | 仕事で使えるAIを、いちばん実践的に。",
    description: "生成AIの使い方・業務効率化の事例・ツール比較・AI副業を実務の目線で。",
    url: SITE_URL,
    siteName: SITE_NAME,
    locale: "ja_JP",
    type: "website",
    ...(hasHero() ? { images: [{ url: heroCover(), width: 1600, height: 1067 }] } : {}),
  },
};

const select = {
  id: true,
  slug: true,
  title: true,
  excerpt: true,
  publishedAt: true,
  createdAt: true,
  readingTime: true,
  category: { select: { slug: true, name: true } },
} as const;

const FEATURED_SECTIONS = ["chatgpt", "ai-business", "ai-tools", "prompt"] as const;

async function getData() {
  const [latest, popular, counts, ...bySection] = await Promise.all([
    prisma.article.findMany({ where: { status: "published" }, select, orderBy: { publishedAt: "desc" }, take: 11 }),
    prisma.article.findMany({ where: { status: "published" }, select, orderBy: { views: { _count: "desc" } }, take: 5 }),
    prisma.category.findMany({ select: { slug: true, _count: { select: { articles: { where: { status: "published" } } } } } }),
    ...FEATURED_SECTIONS.map((slug) =>
      prisma.article.findMany({ where: { status: "published", category: { slug } }, select, orderBy: { publishedAt: "desc" }, take: 16 }),
    ),
  ]);
  return { latest, popular, counts, bySection };
}

export default async function HomePage() {
  const { latest, popular, counts, bySection } = await getData();
  const [lead, ...rest] = latest as CardArticle[];
  const picks = rest.slice(0, 4);
  const more = rest.slice(4, 10);
  const shown = new Set<string>([lead?.id, ...picks.map((a) => a.id), ...more.map((a) => a.id)].filter(Boolean) as string[]);
  const countOf = (slug: string) => counts.find((c) => c.slug === slug)?._count.articles ?? 0;

  const websiteJsonLd = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: SITE_NAME,
    url: SITE_URL,
    inLanguage: "ja",
    publisher: { "@id": `${OPERATOR.url}#organization` },
    potentialAction: {
      "@type": "SearchAction",
      target: { "@type": "EntryPoint", urlTemplate: `${SITE_URL}/search?q={search_term_string}` },
      "query-input": "required name=search_term_string",
    },
  };

  const orgJsonLd = {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": `${OPERATOR.url}#organization`,
    name: OPERATOR.name,
    url: OPERATOR.url,
    email: OPERATOR.email,
    logo: { "@type": "ImageObject", url: `${SITE_URL}/logo.png`, width: 512, height: 512 },
  };

  if (!lead) {
    return (
      <main className="mx-auto max-w-[1240px] px-6 py-32 text-center text-mute">
        記事を準備しています。
      </main>
    );
  }

  return (
    <main>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(orgJsonLd) }} />
      <h1 className="sr-only">AI活用ラボ — ChatGPT・Claude・Geminiの使い方と業務効率化のメディア</h1>

      {/* トップストーリー */}
      <section className="mx-auto max-w-[1240px] px-5 pt-8 md:px-6 md:pt-12">
        <div className="grid gap-10 lg:grid-cols-[minmax(0,1fr)_380px] lg:gap-12">
          <ArticleCard a={lead} variant="lead" priority />
          <div className="lg:border-l lg:border-line lg:pl-12">
            <h2 className="kicker mb-5 text-accent-deep">Pick Up</h2>
            <ul className="divide-y divide-line">
              {picks.map((a) => (
                <li key={a.id} className="py-5 first:pt-0">
                  <ArticleCard a={a} variant="compact" />
                </li>
              ))}
            </ul>
            <Link href="/articles" className="mt-2 flex items-center justify-between border-y-2 border-ink py-3.5 text-[13px] font-bold hover:text-accent">
              すべての記事を見る <span aria-hidden>→</span>
            </Link>
          </div>
        </div>
      </section>

      {/* ランキング */}
      {popular.length > 0 && (
        <section className="mt-20 border-y border-line bg-paper-deep/70">
          <div className="mx-auto max-w-[1240px] px-5 py-12 md:px-6">
            <div className="mb-8 flex items-baseline gap-4">
              <h2 className="text-[22px] font-black tracking-[0.04em] md:text-[26px]">よく読まれている記事</h2>
              <span className="kicker text-mute">Ranking</span>
            </div>
            <ol className="grid gap-x-8 gap-y-8 sm:grid-cols-2 lg:grid-cols-5">
              {(popular as CardArticle[]).map((a, i) => (
                <li key={a.id}>
                  <Link href={`/articles/${a.slug}`} className="group block">
                    <span className="font-[family-name:var(--font-latin)] text-[44px] leading-none font-light text-accent">{String(i + 1).padStart(2, "0")}</span>
                    <p className="mt-3 text-[12px] font-bold text-mute">{categoryMeta(a.category?.slug)?.name ?? a.category?.name ?? "AI活用"}</p>
                    <h3 className="mt-1 line-clamp-3 text-[15px] font-bold leading-[1.6] text-ink">
                      <span className="link-underline">{a.title}</span>
                    </h3>
                  </Link>
                </li>
              ))}
            </ol>
          </div>
        </section>
      )}

      {/* 新着 */}
      <section className="mx-auto mt-20 max-w-[1240px] px-5 md:px-6">
        <SectionHeading ja="新着記事" en="Latest" href="/articles" />
        <div className="grid gap-x-8 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">
          {more.map((a) => (
            <ArticleCard key={a.id} a={a} />
          ))}
        </div>
      </section>

      {/* テーマから探す */}
      <section className="mx-auto mt-24 max-w-[1240px] px-5 md:px-6">
        <SectionHeading ja="テーマから探す" en="Themes" />
        <div className="grid grid-cols-2 gap-3 md:grid-cols-3 md:gap-4">
          {CATEGORIES.map((c) => (
            <Link key={c.slug} href={`/category/${c.slug}`} className="group relative block aspect-[4/3] overflow-hidden bg-ink md:aspect-[16/10]">
              <Image src={categoryCover(c.slug)} alt="" fill sizes="(min-width: 768px) 400px, 50vw" className="img-zoom object-cover opacity-75" />
              <div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/55 to-black/5" />
              <div className="absolute inset-x-0 bottom-0 p-4 md:p-6">
                <p className="kicker text-white/80">{c.en}</p>
                <p className="mt-1 text-[16px] font-black text-white md:text-[21px]">{c.name}</p>
                <p className="mt-1 hidden text-[12px] text-white/80 md:block">{countOf(c.slug)}本の記事</p>
              </div>
            </Link>
          ))}
        </div>
      </section>

      {/* カテゴリ別 */}
      {FEATURED_SECTIONS.map((slug, idx) => {
        const meta = CATEGORIES.find((c) => c.slug === slug)!;
        const pool = bySection[idx] as CardArticle[];
        // まだ載せていない記事を優先し、足りなければ既出の記事で4本にそろえる
        const fresh = pool.filter((a) => !shown.has(a.id));
        const items = [...fresh, ...pool.filter((a) => shown.has(a.id))].slice(0, 4);
        if (items.length === 0) return null;
        items.forEach((a) => shown.add(a.id));
        const [first, ...others] = items;
        return (
          <section key={slug} className="mx-auto mt-24 max-w-[1240px] px-5 md:px-6">
            <SectionHeading ja={meta.name} en={meta.en} href={`/category/${slug}`} />
            <div className="grid gap-10 lg:grid-cols-[1fr_1fr] lg:gap-12">
              <ArticleCard a={first} variant="lead" sizes="(min-width: 1024px) 600px, 100vw" />
              <ul className="divide-y divide-line">
                {others.map((a) => (
                  <li key={a.id} className="py-6 first:pt-0">
                    <ArticleCard a={a} variant="compact" />
                  </li>
                ))}
              </ul>
            </div>
          </section>
        );
      })}

      {/* 運営 */}
      <section className="mx-auto mt-28 max-w-[1240px] px-5 md:px-6">
        <div className="relative overflow-hidden bg-ink">
          <Image src={heroCover()} alt="" fill sizes="(min-width: 1240px) 1240px, 100vw" className="object-cover opacity-45" />
          <div className="absolute inset-0 bg-gradient-to-r from-black/85 via-black/55 to-transparent" />
          <div className="relative max-w-xl px-7 py-16 md:px-14 md:py-24">
            <p className="kicker text-white/80">Operated by {OPERATOR.name}</p>
            <h2 className="headline mt-4 text-[26px] text-white md:text-[36px]">AIを、現場で動くかたちに。</h2>
            <p className="mt-5 text-[14px] leading-[1.95] text-white/80">
              AI活用ラボは、SNS運用代行とAIシステムの導入支援を手がける{OPERATOR.name}が運営しています。記事で紹介した使い方を自社の業務に落とし込みたい方は、お気軽にご相談ください。
            </p>
            <a href={OPERATOR.url} target="_blank" rel="noopener" className="mt-8 inline-flex items-center gap-3 bg-accent px-6 py-3.5 text-[14px] font-bold text-white transition-colors hover:bg-accent-deep">
              AI導入について相談する <span aria-hidden>→</span>
            </a>
          </div>
        </div>
      </section>
    </main>
  );
}
