/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { formatDate } from "@/lib/utils";

export const revalidate = 60;

async function getArticles() {
  return prisma.article.findMany({
    where: { status: "published" },
    include: { category: true, _count: { select: { views: true } } },
    orderBy: { publishedAt: "desc" },
    take: 12,
  });
}

async function getFeatured() {
  return prisma.article.findMany({
    where: { status: "published" },
    include: { category: true },
    orderBy: { views: { _count: "desc" } },
    take: 3,
  });
}

const CATEGORY_COLORS: Record<string, string> = {
  chatgpt: "bg-emerald-100 text-emerald-700",
  "ai-business": "bg-purple-100 text-purple-700",
  "ai-tools": "bg-amber-100 text-amber-700",
  prompt: "bg-red-100 text-red-700",
  "ai-income": "bg-violet-100 text-violet-700",
  "ai-news": "bg-cyan-100 text-cyan-700",
};

export default async function HomePage() {
  const [articles, featured] = await Promise.all([getArticles(), getFeatured()]);

  return (
    <main>
      {/* Hero */}
      <section className="bg-gradient-to-br from-purple-900 via-purple-800 to-indigo-900 text-white py-16">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <div className="text-5xl mb-4">🤖</div>
          <h1 className="text-4xl font-bold mb-4">AI活用ラボ</h1>
          <p className="text-purple-200 text-lg mb-8">ChatGPT・Claude・Geminiの使い方から、AI副業・業務効率化まで<br />最新情報を毎日お届けします</p>
          <div className="flex flex-wrap justify-center gap-3">
            {["ChatGPT活用術","AI業務効率化","プロンプト技術","AI副業"].map(tag => (
              <span key={tag} className="bg-white/10 text-white text-sm px-4 py-1.5 rounded-full">{tag}</span>
            ))}
          </div>
        </div>
      </section>

      <div className="max-w-6xl mx-auto px-4 py-10">
        {/* Featured */}
        {featured.length > 0 && (
          <section className="mb-12">
            <h2 className="text-xl font-bold text-gray-900 mb-5 flex items-center gap-2">
              <span>🔥</span> 人気記事
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
              {featured.map(article => (
                <Link key={article.id} href={`/articles/${article.slug}`}
                  className="group block bg-white rounded-xl border border-gray-100 overflow-hidden hover:shadow-md transition-shadow">
                  <div className="aspect-video bg-gradient-to-br from-purple-100 to-indigo-100 flex items-center justify-center text-4xl">
                    {article.category?.slug === "chatgpt" ? "💬" : article.category?.slug === "ai-tools" ? "🛠" : article.category?.slug === "prompt" ? "✍️" : "🤖"}
                  </div>
                  <div className="p-4">
                    {article.category && (
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium mb-2 inline-block ${CATEGORY_COLORS[article.category.slug] || "bg-gray-100 text-gray-600"}`}>
                        {article.category.name}
                      </span>
                    )}
                    <h3 className="font-bold text-gray-900 text-sm line-clamp-2 group-hover:text-purple-600 transition-colors">{article.title}</h3>
                    <p className="text-xs text-gray-400 mt-2">{formatDate(article.publishedAt || article.createdAt)}</p>
                  </div>
                </Link>
              ))}
            </div>
          </section>
        )}

        {/* Article Grid */}
        <section>
          <div className="flex items-center justify-between mb-5">
            <h2 className="text-xl font-bold text-gray-900">📝 最新記事</h2>
            <Link href="/articles" className="text-purple-600 text-sm hover:underline">すべての記事 →</Link>
          </div>
          {articles.length === 0 ? (
            <div className="text-center py-20 text-gray-400">
              <p className="text-4xl mb-4">📝</p>
              <p>記事を準備中です。しばらくお待ちください。</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
              {articles.map(article => (
                <Link key={article.id} href={`/articles/${article.slug}`}
                  className="group block bg-white rounded-xl border border-gray-100 overflow-hidden hover:shadow-md transition-shadow">
                  <div className="aspect-video bg-gradient-to-br from-gray-50 to-gray-100 flex items-center justify-center text-3xl">
                    {article.category?.slug === "chatgpt" ? "💬" : article.category?.slug === "ai-tools" ? "🛠" : article.category?.slug === "prompt" ? "✍️" : article.category?.slug === "ai-income" ? "💰" : "🤖"}
                  </div>
                  <div className="p-4">
                    {article.category && (
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium mb-2 inline-block ${CATEGORY_COLORS[article.category.slug] || "bg-gray-100 text-gray-600"}`}>
                        {article.category.name}
                      </span>
                    )}
                    <h3 className="font-bold text-gray-900 text-sm line-clamp-2 group-hover:text-purple-600 transition-colors mb-1">{article.title}</h3>
                    <p className="text-xs text-gray-500 line-clamp-2">{article.excerpt}</p>
                    <div className="flex items-center justify-between mt-3">
                      <span className="text-xs text-gray-400">{formatDate(article.publishedAt || article.createdAt)}</span>
                      <span className="text-xs text-gray-400">👁 {(article._count?.views || 0).toLocaleString()}</span>
                    </div>
                  </div>
                </Link>
              ))}
            </div>
          )}
        </section>

        {/* CTA */}
        <section className="mt-16 bg-gradient-to-r from-purple-600 to-indigo-600 rounded-2xl p-8 text-center text-white">
          <h2 className="text-2xl font-bold mb-2">AIで業務効率を劇的に改善しませんか？</h2>
          <p className="text-purple-200 mb-5">ChatGPT・Claude・Geminiを使いこなすノウハウを無料でお届けします</p>
          <a href="mailto:contact@ai-media.jp" className="bg-white text-purple-600 font-semibold px-6 py-3 rounded-full hover:bg-purple-50 transition-colors inline-block">
            お問い合わせ・相談はこちら →
          </a>
        </section>
      </div>
    </main>
  );
}
