/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { formatDate } from "@/lib/utils";
import type { Metadata } from "next";

export const revalidate = 60;

const SITE_URL = "https://media.seasonsezon.co.jp";

export const metadata: Metadata = {
  title: "AI活用ラボ | ChatGPT・Claude・Geminiの使い方・副業・業務効率化",
  description: "ChatGPT・Claude・Geminiなど最新AIツールの使い方・活用事例・AI副業情報を毎日お届け。初心者から上級者まで役立つ実践的なAI情報メディアです。",
  keywords: "ChatGPT,Claude,Gemini,AI活用,AI副業,業務効率化,プロンプト,AIツール",
  alternates: { canonical: SITE_URL },
  openGraph: {
    title: "AI活用ラボ | ChatGPT・Claude・Geminiの使い方・副業・業務効率化",
    description: "最新AIツールの使い方・活用事例・AI副業情報を毎日お届け",
    url: SITE_URL,
    siteName: "AI活用ラボ",
    locale: "ja_JP",
    type: "website",
  },
};

async function getArticles() {
  return prisma.article.findMany({
    where: { status: "published" },
    include: { category: true, _count: { select: { views: true } } },
    orderBy: { publishedAt: "desc" },
    take: 12,
  });
}

async function getFeatured() {
  return prisma.article.findMany({
    where: { status: "published" },
    include: { category: true },
    orderBy: { views: { _count: "desc" } },
    take: 3,
  });
}

const CATEGORY_COLORS: Record<string, string> = {
  chatgpt: "bg-emerald-100 text-emerald-700",
  "ai-business": "bg-purple-100 text-purple-700",
  "ai-tools": "bg-amber-100 text-amber-700",
  prompt: "bg-red-100 text-red-700",
  "ai-income": "bg-violet-100 text-violet-700",
  "ai-news": "bg-cyan-100 text-cyan-700",
};

async function getStats() {
  const [totalArticles, totalViews] = await Promise.all([
    prisma.article.count({ where: { status: "published" } }),
    prisma.articleView.count(),
  ]);
  return { totalArticles, totalViews };
}

export default async function HomePage() {
  const [articles, featured, stats] = await Promise.all([getArticles(), getFeatured(), getStats()]);

  const websiteJsonLd = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "AI活用ラボ",
    url: SITE_URL,
    description: "ChatGPT・Claude・Geminiなど最新AIツールの使い方・活用事例・AI副業情報メディア",
    inLanguage: "ja",
    potentialAction: {
      "@type": "SearchAction",
      target: { "@type": "EntryPoint", urlTemplate: `${SITE_URL}/search?q={search_term_string}` },
      "query-input": "required name=search_term_string",
    },
  };

  const orgJsonLd = {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "AI活用ラボ",
    url: SITE_URL,
    contactPoint: { "@type": "ContactPoint", email: "contact@ai-media.jp", contactType: "customer support" },
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(orgJsonLd) }} />
    <main>
      {/* Hero */}
      <section className="bg-gradient-to-br from-purple-900 via-purple-800 to-indigo-900 text-white py-16">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <div className="text-5xl mb-4">🤖</div>
          <h1 className="text-4xl font-bold mb-4">AI活用ラボ</h1>
          <p className="text-purple-200 text-lg mb-8">ChatGPT・Claude・Geminiの使い方から、AI副業・業務効率化まで<br />最新情報を毎日お届けします</p>
          {/* 統計バッジ */}
          <div className="flex items-center justify-center gap-6 mb-6">
            <div className="text-center">
              <div className="text-2xl font-bold text-white">{stats.totalArticles}</div>
              <div className="text-xs text-purple-300">公開記事数</div>
            </div>
            <div className="w-px h-8 bg-white/20" />
            <div className="text-center">
              <div className="text-2xl font-bold text-white">毎日更新</div>
              <div className="text-xs text-purple-300">新着記事</div>
            </div>
            <div className="w-px h-8 bg-white/20" />
            <div className="text-center">
              <div className="text-2xl font-bold text-white">無料</div>
              <div className="text-xs text-purple-300">全記事閲覧</div>
            </div>
          </div>
          <form action="/search" method="get" className="max-w-xl mx-auto mb-6">
            <div className="flex gap-2">
              <input type="text" name="q" placeholder="記事を検索する（例: ChatGPT使い方）"
                className="flex-1 bg-white/10 border border-white/30 text-white placeholder-purple-300 rounded-xl px-4 py-3 text-sm focus:outline-none focus:bg-white/20 focus:border-white/60 transition" />
              <button type="submit" className="bg-white text-purple-700 font-semibold px-5 py-3 rounded-xl text-sm hover:bg-purple-50 transition-colors">
                検索
              </button>
            </div>
          </form>
          <div className="flex flex-wrap justify-center gap-2">
            {[
              { href: "/category/chatgpt", label: "💬 ChatGPT活用術" },
              { href: "/category/ai-business", label: "⚡ AI業務効率化" },
              { href: "/category/prompt", label: "✍️ プロンプト技術" },
              { href: "/category/ai-income", label: "💰 AI副業" },
              { href: "/category/ai-tools", label: "🛠 AIツール比較" },
              { href: "/category/ai-news", label: "📰 AI最新ニュース" },
            ].map((tag: any) => (
              <Link key={tag.href} href={tag.href} className="bg-white/10 hover:bg-white/20 text-white text-sm px-4 py-1.5 rounded-full transition-colors border border-white/20">
                {tag.label}
              </Link>
            ))}
          </div>
        </div>
      </section>

      <div className="max-w-6xl mx-auto px-4 py-10">
        {/* Featured */}
        {featured.length > 0 && (
          <section className="mb-12">
            <h2 className="text-xl font-bold text-gray-900 mb-5 flex items-center gap-2">
              <span>🔥</span> 人気記事
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
              {featured.map((article: any) => (
                <Link key={article.id} href={`/articles/${article.slug}`}
                  className="group block bg-white rounded-xl border border-gray-100 overflow-hidden hover:shadow-md transition-shadow">
                  <div className="aspect-video bg-gradient-to-br from-purple-100 to-indigo-100 flex items-center justify-center text-4xl">
                    {article.category?.slug === "chatgpt" ? "💬" : article.category?.slug === "ai-tools" ? "🛠" : article.category?.slug === "prompt" ? "✍️" : "🤖"}
                  </div>
                  <div className="p-4">
                    {article.category && (
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium mb-2 inline-block ${CATEGORY_COLORS[article.category.slug] || "bg-gray-100 text-gray-600"}`}>
                        {article.category.name}
                      </span>
                    )}
                    <h3 className="font-bold text-gray-900 text-sm line-clamp-2 group-hover:text-purple-600 transition-colors">{article.title}</h3>
                    <p className="text-xs text-gray-400 mt-2">{formatDate(article.publishedAt || article.createdAt)}</p>
                  </div>
                </Link>
              ))}
            </div>
          </section>
        )}

        {/* Article Grid */}
        <section>
          <div className="flex items-center justify-between mb-5">
            <h2 className="text-xl font-bold text-gray-900">📝 最新記事</h2>
            <Link href="/articles" className="text-purple-600 text-sm hover:underline">すべての記事 →</Link>
          </div>
          {articles.length === 0 ? (
            <div className="text-center py-20 text-gray-400">
              <p className="text-4xl mb-4">📝</p>
              <p>記事を準備中です。しばらくお待ちください。</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
              {articles.map((article: any) => (
                <Link key={article.id} href={`/articles/${article.slug}`}
                  className="group block bg-white rounded-xl border border-gray-100 overflow-hidden hover:shadow-md transition-shadow">
                  <div className="aspect-video bg-gradient-to-br from-gray-50 to-gray-100 flex items-center justify-center text-3xl">
                    {article.category?.slug === "chatgpt" ? "💬" : article.category?.slug === "ai-tools" ? "🛠" : article.category?.slug === "prompt" ? "✍️" : article.category?.slug === "ai-income" ? "💰" : "🤖"}
                  </div>
                  <div className="p-4">
                    {article.category && (
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium mb-2 inline-block ${CATEGORY_COLORS[article.category.slug] || "bg-gray-100 text-gray-600"}`}>
                        {article.category.name}
                      </span>
                    )}
                    <h3 className="font-bold text-gray-900 text-sm line-clamp-2 group-hover:text-purple-600 transition-colors mb-1">{article.title}</h3>
                    <p className="text-xs text-gray-500 line-clamp-2">{article.excerpt}</p>
                    <div className="flex items-center justify-between mt-3">
                      <span className="text-xs text-gray-400">{formatDate(article.publishedAt || article.createdAt)}</span>
                      <span className="text-xs text-gray-400">👁 {(article._count?.views || 0).toLocaleString()}</span>
                    </div>
                  </div>
                </Link>
              ))}
            </div>
          )}
        </section>

        {/* CTA */}
        <section className="mt-16 bg-gradient-to-r from-purple-600 to-indigo-600 rounded-2xl p-8 text-center text-white">
          <h2 className="text-2xl font-bold mb-2">AIで業務効率を劇的に改善しませんか？</h2>
          <p className="text-purple-200 mb-5">ChatGPT・Claude・Geminiを使いこなすノウハウを無料でお届けします</p>
          <a href="mailto:contact@ai-media.jp" className="bg-white text-purple-600 font-semibold px-6 py-3 rounded-full hover:bg-purple-50 transition-colors inline-block">
            お問い合わせ・相談はこちら →
          </a>
        </section>
      </div>
    </main>
    </>
  );
}
