/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

export default function GeneratePage() {
  const [keywords, setKeywords] = useState<any[]>([]);
  const [categories, setCategories] = useState<any[]>([]);
  const [jobs, setJobs] = useState<any[]>([]);
  const [generating, setGenerating] = useState(false);
  const [batchRunning, setBatchRunning] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [form, setForm] = useState({ keyword: "", keywordId: "", categoryId: "", autoPublish: true });

  useEffect(() => {
    fetch("/api/keywords?status=pending").then(r => r.json()).then(setKeywords);
    fetch("/api/analytics?days=1").then(() => {});
    fetch("/api/generate").then(r => r.json()).then(setJobs);
    // カテゴリ一覧を articles API から取得
  }, []);

  async function handleGenerate() {
    if (!form.keyword) return;
    setGenerating(true);
    setResult(null);
    try {
      const res = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });
      const data = await res.json();
      if (res.ok) {
        setResult({ success: true, article: data.article });
        fetch("/api/generate").then(r => r.json()).then(setJobs);
        fetch("/api/keywords?status=pending").then(r => r.json()).then(setKeywords);
      } else {
        setResult({ success: false, error: data.error });
      }
    } catch (e: any) {
      setResult({ success: false, error: e.message });
    } finally {
      setGenerating(false);
    }
  }

  async function batchGenerate() {
    if (!confirm(`未着手キーワード${keywords.slice(0,5).length}件の記事を自動生成しますか？`)) return;
    setBatchRunning(true);
    for (const kw of keywords.slice(0, 5)) {
      try {
        await fetch("/api/generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ keyword: kw.keyword, keywordId: kw.id, autoPublish: true }),
        });
        await new Promise(r => setTimeout(r, 2000)); // API rate limit対策
      } catch {}
    }
    fetch("/api/generate").then(r => r.json()).then(setJobs);
    fetch("/api/keywords?status=pending").then(r => r.json()).then(setKeywords);
    setBatchRunning(false);
    alert("バッチ生成が完了しました");
  }

  const STATUS_ICON: Record<string, string> = { pending:"⏳", running:"🔄", completed:"✅", failed:"❌" };

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">🤖 AI記事生成</h1>
          <p className="text-sm text-gray-500">Claude AIが自動でSEO最適化記事を生成します</p>
        </div>
        <button onClick={batchGenerate} disabled={batchRunning || keywords.length === 0}
          className="bg-emerald-600 hover:bg-emerald-700 disabled:opacity-40 text-white text-sm px-4 py-2 rounded-lg font-medium">
          {batchRunning ? "一括生成中..." : `🚀 一括生成 (${Math.min(keywords.length, 5)}件)`}
        </button>
      </div>

      <div className="grid grid-cols-2 gap-5">
        {/* 生成フォーム */}
        <div className="bg-white rounded-xl border border-gray-100 p-5 space-y-4">
          <h2 className="font-semibold text-gray-800">記事を生成する</h2>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">キーワード（未着手リストから選択 or 直接入力）</label>
            <select
              value={form.keywordId}
              onChange={e => {
                const kw = keywords.find(k => k.id === e.target.value);
                setForm(f => ({ ...f, keywordId: e.target.value, keyword: kw?.keyword || f.keyword }));
              }}
              className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none mb-2"
            >
              <option value="">-- キーワードを選択 --</option>
              {keywords.map(kw => (
                <option key={kw.id} value={kw.id}>
                  {kw.keyword} (月間{kw.searchVolume.toLocaleString()}回)
                </option>
              ))}
            </select>
            <input
              value={form.keyword}
              onChange={e => setForm(f => ({ ...f, keyword: e.target.value, keywordId: "" }))}
              placeholder="または直接キーワードを入力..."
              className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none"
            />
          </div>

          <div className="flex items-center gap-3">
            <input type="checkbox" id="autoPublish" checked={form.autoPublish}
              onChange={e => setForm(f => ({ ...f, autoPublish: e.target.checked }))}
              className="rounded text-purple-600" />
            <label htmlFor="autoPublish" className="text-sm text-gray-700">生成後に自動公開する</label>
          </div>

          <button
            onClick={handleGenerate}
            disabled={generating || !form.keyword}
            className="w-full bg-purple-600 hover:bg-purple-700 disabled:opacity-40 text-white py-3 rounded-lg font-semibold text-sm transition-colors"
          >
            {generating ? (
              <span className="flex items-center justify-center gap-2">
                <span className="animate-spin">⚙️</span> Claude AIが記事を生成中...
              </span>
            ) : "✨ 記事を生成する"}
          </button>

          {result && (
            <div className={`p-4 rounded-lg text-sm ${result.success ? "bg-emerald-50 border border-emerald-200" : "bg-red-50 border border-red-200"}`}>
              {result.success ? (
                <div>
                  <p className="font-semibold text-emerald-700 mb-1">✅ 生成完了！</p>
                  <p className="text-emerald-600 mb-2">{result.article.title}</p>
                  <Link href={`/admin/articles/${result.article.id}`} className="text-purple-600 hover:underline">
                    記事を確認する →
                  </Link>
                </div>
              ) : (
                <div>
                  <p className="font-semibold text-red-700 mb-1">❌ 生成失敗</p>
                  <p className="text-red-600 text-xs">{result.error}</p>
                  {result.error?.includes("API") && (
                    <p className="text-red-500 text-xs mt-1">.envのANTHROPIC_API_KEYを設定してください</p>
                  )}
                </div>
              )}
            </div>
          )}
        </div>

        {/* キーワード一覧 */}
        <div className="bg-white rounded-xl border border-gray-100 p-5">
          <div className="flex items-center justify-between mb-4">
            <h2 className="font-semibold text-gray-800">未着手キーワード ({keywords.length}件)</h2>
            <Link href="/admin/keywords/new" className="text-purple-600 text-xs hover:underline">+ 追加</Link>
          </div>
          {keywords.length === 0 ? (
            <p className="text-gray-400 text-sm text-center py-8">未着手キーワードがありません</p>
          ) : (
            <div className="space-y-2 max-h-80 overflow-y-auto">
              {keywords.map(kw => (
                <div key={kw.id}
                  className="flex items-center gap-3 p-2.5 rounded-lg border border-gray-100 hover:border-purple-200 cursor-pointer transition-colors"
                  onClick={() => setForm(f => ({ ...f, keyword: kw.keyword, keywordId: kw.id }))}
                >
                  <div className="flex-1 min-w-0">
                    <p className="text-sm text-gray-800 font-medium truncate">{kw.keyword}</p>
                    <div className="flex gap-3 mt-0.5">
                      <span className="text-xs text-gray-400">月間 {kw.searchVolume.toLocaleString()}回</span>
                      <span className={`text-xs font-medium ${kw.priority === "high" ? "text-red-500" : kw.priority === "medium" ? "text-yellow-500" : "text-gray-400"}`}>
                        {kw.priority === "high" ? "高優先" : kw.priority === "medium" ? "中優先" : "低優先"}
                      </span>
                    </div>
                  </div>
                  <div className="text-right">
                    <div className="text-xs text-gray-400">難易度</div>
                    <div className={`text-sm font-bold ${kw.difficulty < 40 ? "text-emerald-600" : kw.difficulty < 60 ? "text-yellow-600" : "text-red-600"}`}>
                      {kw.difficulty}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* 生成履歴 */}
      <div className="bg-white rounded-xl border border-gray-100 p-5">
        <h2 className="font-semibold text-gray-800 mb-4">生成履歴</h2>
        {jobs.length === 0 ? (
          <p className="text-gray-400 text-sm text-center py-8">生成履歴がありません</p>
        ) : (
          <div className="space-y-2">
            {jobs.map((job: any) => (
              <div key={job.id} className="flex items-center gap-3 py-2 border-b border-gray-50 last:border-0">
                <span>{STATUS_ICON[job.status]}</span>
                <div className="flex-1">
                  <p className="text-sm text-gray-800">{job.keyword}</p>
                  {job.result && <p className="text-xs text-gray-400">{job.result}</p>}
                  {job.errorMsg && <p className="text-xs text-red-400">{job.errorMsg}</p>}
                </div>
                <span className="text-xs text-gray-400">{new Date(job.createdAt).toLocaleDateString("ja-JP")}</span>
                {job.articleId && (
                  <Link href={`/admin/articles/${job.articleId}`} className="text-xs text-purple-600 hover:underline">記事を見る</Link>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
