/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI v2056.8
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * Redistribution / derivative-work / reverse-engineering prohibited
 * (著作権法 / 不正競争防止法 / 当社利用規約 第 8 条).
 * License inquiries: nomura.y@soloptilink.com
 * ----------------------------------------------------------------*/
import Link from "next/link";
import type { Metadata } from "next";
import { prisma } from "@/lib/prisma";
import ArticleCard, { type CardArticle } from "@/components/media/ArticleCard";
import { CATEGORIES, SITE_NAME, SITE_URL } from "@/lib/media";

export const revalidate = 300;

export const metadata: Metadata = {
  title: "記事一覧｜ChatGPT・Claude・Geminiの使い方と業務活用",
  description:
    "ChatGPT・Claude・Geminiなど生成AIの使い方・業務効率化・ツール比較・AI副業に関する記事の一覧です。",
  alternates: { canonical: `${SITE_URL}/articles` },
  openGraph: {
    title: `すべての記事 | ${SITE_NAME}`,
    url: `${SITE_URL}/articles`,
    siteName: SITE_NAME,
    locale: "ja_JP",
    type: "website",
  },
};

export default async function ArticlesPage() {
  const articles = (await prisma.article.findMany({
    where: { status: "published" },
    select: {
      id: true,
      slug: true,
      title: true,
      excerpt: true,
      publishedAt: true,
      createdAt: true,
      readingTime: true,
      category: { select: { slug: true, name: true } },
    },
    orderBy: { publishedAt: "desc" },
    take: 120,
  })) as CardArticle[];

  const breadcrumbJsonLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "ホーム", item: SITE_URL },
      {
        "@type": "ListItem",
        position: 2,
        name: "すべての記事",
        item: `${SITE_URL}/articles`,
      },
    ],
  };

  return (
    <main className="mx-auto max-w-[1240px] px-5 pt-12 md:px-6 md:pt-16">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      <div className="flex flex-col gap-6 border-b-2 border-ink pb-8 md:flex-row md:items-end md:justify-between">
        <div>
          <p className="kicker text-accent-deep">All Articles</p>
          <h1 className="mt-2 text-[30px] font-black tracking-[0.04em] md:text-[40px]">
            すべての記事
          </h1>
          <p className="mt-2 text-[13px] text-mute">
            {articles.length}本の記事
          </p>
        </div>
        <nav aria-label="カテゴリ" className="flex flex-wrap gap-2">
          {CATEGORIES.map((c) => (
            <Link
              key={c.slug}
              href={`/category/${c.slug}`}
              className="border border-line px-3 py-1.5 text-[12px] font-bold text-ink-soft hover:border-ink hover:text-ink"
            >
              {c.name}
            </Link>
          ))}
        </nav>
      </div>

      {articles.length === 0 ? (
        <p className="py-32 text-center text-mute">記事を準備しています。</p>
      ) : (
        <section aria-labelledby="list-heading">
          <h2 id="list-heading" className="sr-only">
            新着順の記事
          </h2>
          <div className="mt-12 grid gap-x-8 gap-y-14 sm:grid-cols-2 lg:grid-cols-3">
            {articles.map((a, i) => (
              <ArticleCard key={a.id} a={a} priority={i === 0} />
            ))}
          </div>
        </section>
      )}
    </main>
  );
}
