/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { formatDate } from "@/lib/utils";

export const revalidate = 60;

export default async function ArticlesPage() {
  const articles = await prisma.article.findMany({
    where: { status: "published" },
    include: { category: true, _count: { select: { views: true } } },
    orderBy: { publishedAt: "desc" },
    take: 50,
  });

  return (
    <main className="max-w-5xl mx-auto px-4 py-10">
      <h1 className="text-2xl font-bold text-gray-900 mb-6">すべての記事 ({articles.length}件)</h1>
      <div className="space-y-4">
        {articles.map(article => (
          <Link key={article.id} href={`/articles/${article.slug}`}
            className="flex gap-4 bg-white rounded-xl border border-gray-100 p-4 hover:shadow-md transition-shadow group">
            <div className="w-20 h-20 flex-shrink-0 bg-gradient-to-br from-purple-100 to-indigo-100 rounded-lg flex items-center justify-center text-2xl">
              🤖
            </div>
            <div className="flex-1 min-w-0">
              <h2 className="font-bold text-gray-900 group-hover:text-purple-600 transition-colors line-clamp-1">{article.title}</h2>
              <p className="text-sm text-gray-500 line-clamp-2 mt-1">{article.excerpt}</p>
              <div className="flex items-center gap-4 mt-2">
                {article.category && <span className="text-xs text-purple-600">{article.category.name}</span>}
                <span className="text-xs text-gray-400">{formatDate(article.publishedAt || article.createdAt)}</span>
                <span className="text-xs text-gray-400">👁 {(article._count?.views||0).toLocaleString()}</span>
                <span className="text-xs text-gray-400">📖 約{article.readingTime}分</span>
              </div>
            </div>
          </Link>
        ))}
        {articles.length === 0 && (
          <div className="text-center py-20 text-gray-400">記事を準備中です</div>
        )}
      </div>
    </main>
  );
}
