/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * ----------------------------------------------------------------*/
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const days = parseInt(searchParams.get("days") || "30");
    const since = new Date(Date.now() - days * 86400000);

    const [totalViews, todayViews, articles, topArticles, viewsByDay, revenueByDay, totalRevenue] = await Promise.all([
      prisma.articleView.count({ where: { viewedAt: { gte: since } } }),
      prisma.articleView.count({ where: { viewedAt: { gte: new Date(new Date().setHours(0,0,0,0)) } } }),
      prisma.article.count({ where: { status: "published" } }),
      prisma.article.findMany({
        where: { status: "published" },
        include: { _count: { select: { views: true } }, category: true },
        orderBy: { views: { _count: "desc" } },
        take: 10,
      }),
      // PV by day
      prisma.$queryRaw`
        SELECT date(viewedAt) as date, COUNT(*) as count
        FROM ArticleView
        WHERE viewedAt >= ${since.toISOString()}
        GROUP BY date(viewedAt)
        ORDER BY date ASC
      `,
      // Revenue by day
      prisma.$queryRaw`
        SELECT date(date) as date, SUM(amount) as total, type
        FROM Revenue
        WHERE date >= ${since.toISOString()}
        GROUP BY date(date), type
        ORDER BY date ASC
      `,
      prisma.revenue.aggregate({
        where: { date: { gte: since } },
        _sum: { amount: true },
      }),
    ]);

    const totalArticles = await prisma.article.count();
    const draftArticles = await prisma.article.count({ where: { status: "draft" } });
    const keywords = await prisma.keyword.count({ where: { status: "pending" } });

    return NextResponse.json({
      overview: {
        totalViews,
        todayViews,
        publishedArticles: articles,
        totalArticles,
        draftArticles,
        pendingKeywords: keywords,
        monthlyRevenue: totalRevenue._sum.amount || 0,
        projectedMonthlyPV: Math.round(totalViews / days * 30),
      },
      topArticles,
      viewsByDay,
      revenueByDay,
    });
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}

// Record page view
export async function POST(req: NextRequest) {
  try {
    const { articleId, referer } = await req.json();
    if (!articleId) return NextResponse.json({ error: "記事IDが必要" }, { status: 400 });
    await prisma.articleView.create({ data: { articleId, referer } });
    return NextResponse.json({ success: true });
  } catch {
    return NextResponse.json({ error: "記録失敗" }, { status: 500 });
  }
}
