/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI v2056.8
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * Redistribution / derivative-work / reverse-engineering prohibited
 * (著作権法 / 不正競争防止法 / 当社利用規約 第 8 条).
 * License inquiries: nomura.y@soloptilink.com
 * ----------------------------------------------------------------*/
import Link from "next/link";

export default function NotFound() {
  return (
    <main className="grid min-h-screen place-items-center bg-paper px-5">
      <div className="max-w-md text-center">
        <p className="font-[family-name:var(--font-latin)] text-[96px] leading-none font-extralight text-accent">404</p>
        <h1 className="mt-6 text-[22px] font-black">ページが見つかりません</h1>
        <p className="mt-3 text-[14px] leading-[1.9] text-ink-soft">お探しのページは移動または削除された可能性があります。</p>
        <div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row">
          <Link href="/" className="bg-ink px-6 py-3 text-[14px] font-bold text-white hover:bg-accent">トップへ戻る</Link>
          <Link href="/articles" className="border border-ink px-6 py-3 text-[14px] font-bold text-ink hover:bg-ink hover:text-white">記事一覧を見る</Link>
        </div>
      </div>
    </main>
  );
}
