/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
import Link from "next/link";

export default function NotFound() {
  return (
    <div className="min-h-screen bg-white flex items-center justify-center px-4">
      <div className="text-center max-w-md">
        <div className="text-7xl mb-6">🤖</div>
        <h1 className="text-4xl font-bold text-gray-900 mb-3">404</h1>
        <p className="text-xl font-semibold text-gray-700 mb-2">ページが見つかりません</p>
        <p className="text-gray-500 mb-8 text-sm leading-relaxed">
          お探しのページは移動または削除された可能性があります。<br />
          以下のリンクからAI活用ラボをご覧ください。
        </p>
        <div className="flex flex-col sm:flex-row gap-3 justify-center">
          <Link href="/"
            className="bg-purple-600 text-white px-6 py-3 rounded-xl font-semibold hover:bg-purple-700 transition-colors">
            ホームへ戻る
          </Link>
          <Link href="/articles"
            className="border border-purple-200 text-purple-600 px-6 py-3 rounded-xl font-semibold hover:bg-purple-50 transition-colors">
            記事一覧を見る
          </Link>
        </div>
        <div className="mt-10">
          <p className="text-xs text-gray-400 mb-3">よく読まれているカテゴリ</p>
          <div className="flex flex-wrap justify-center gap-2">
            {[
              { href: "/category/chatgpt", label: "💬 ChatGPT活用術" },
              { href: "/category/prompt", label: "✍️ プロンプト技術" },
              { href: "/category/ai-income", label: "💰 AI副業" },
              { href: "/category/ai-tools", label: "🛠 AIツール比較" },
            ].map(c => (
              <Link key={c.href} href={c.href}
                className="text-xs bg-gray-100 text-gray-600 px-3 py-1.5 rounded-full hover:bg-purple-100 hover:text-purple-700 transition-colors">
                {c.label}
              </Link>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
