/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
"use client";
import { useEffect, useRef } from "react";

interface Props {
  articleTitle: string;
}

declare global { interface Window { gtag?: (...args: unknown[]) => void; } }

export default function ScrollDepthTracker({ articleTitle }: Props) {
  const milestones = useRef(new Set<number>());

  useEffect(() => {
    const handleScroll = () => {
      const scrollTop = window.scrollY;
      const docHeight = document.documentElement.scrollHeight - window.innerHeight;
      if (docHeight <= 0) return;
      const pct = Math.round((scrollTop / docHeight) * 100);
      for (const milestone of [25, 50, 75, 90, 100]) {
        if (pct >= milestone && !milestones.current.has(milestone)) {
          milestones.current.add(milestone);
          if (window.gtag) {
            window.gtag("event", "scroll_depth", {
              percent_scrolled: milestone,
              page_title: articleTitle,
            });
          }
        }
      }
    };
    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => window.removeEventListener("scroll", handleScroll);
  }, [articleTitle]);

  return null;
}
