"use client";
/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
import { useState } from "react";

interface Props {
  url: string;
  title: string;
  large?: boolean;
}

declare global { interface Window { gtag?: (...args: unknown[]) => void; } }

function trackShare(method: string, title: string) {
  if (typeof window !== "undefined" && window.gtag) {
    window.gtag("event", "share", { method, content_type: "article", item_id: title });
  }
}

export default function ShareButtons({ url, title, large }: Props) {
  const [copied, setCopied] = useState(false);

  const encodedUrl = encodeURIComponent(url);
  const encodedTitle = encodeURIComponent(title);

  const copyUrl = async () => {
    try {
      await navigator.clipboard.writeText(url);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      trackShare("copy", title);
    } catch {
      // fallback
    }
  };

  const btnClass = large
    ? "flex items-center gap-2 px-5 py-2.5 rounded-full font-semibold text-sm transition-all hover:opacity-90 hover:scale-105"
    : "flex items-center gap-1.5 px-3 py-1.5 rounded-full font-medium text-xs transition-all hover:opacity-90";

  return (
    <div className={`flex items-center flex-wrap gap-2 ${large ? "justify-center" : ""}`}>
      {/* X (Twitter) */}
      <a
        href={`https://twitter.com/intent/tweet?text=${encodedTitle}&url=${encodedUrl}&hashtags=AI活用,ChatGPT`}
        target="_blank"
        rel="noopener noreferrer"
        onClick={() => trackShare("X", title)}
        className={`${btnClass} bg-black text-white`}
        aria-label="Xでシェア"
      >
        <svg className={large ? "w-4 h-4" : "w-3 h-3"} viewBox="0 0 24 24" fill="currentColor">
          <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-4.714-6.231-5.401 6.231H2.747l7.73-8.835L1.254 2.25H8.08l4.259 5.63zm-1.161 17.52h1.833L7.084 4.126H5.117z"/>
        </svg>
        {large ? "Xでシェア" : "X"}
      </a>

      {/* LINE */}
      <a
        href={`https://social-plugins.line.me/lineit/share?url=${encodedUrl}`}
        target="_blank"
        rel="noopener noreferrer"
        onClick={() => trackShare("LINE", title)}
        className={`${btnClass} bg-[#06C755] text-white`}
        aria-label="LINEでシェア"
      >
        <svg className={large ? "w-4 h-4" : "w-3 h-3"} viewBox="0 0 24 24" fill="currentColor">
          <path d="M19.365 9.863c.349 0 .63.285.63.631 0 .345-.281.63-.63.63H17.61v1.125h1.755c.349 0 .63.283.63.63 0 .344-.281.629-.63.629h-2.386c-.345 0-.627-.285-.627-.629V8.108c0-.345.282-.63.63-.63h2.386c.346 0 .627.285.627.63 0 .349-.281.63-.63.63H17.61v1.125h1.755zm-3.855 3.016c0 .27-.174.51-.432.596-.064.021-.133.031-.199.031-.211 0-.391-.09-.51-.25l-2.443-3.317v2.94c0 .344-.279.629-.631.629-.346 0-.626-.285-.626-.629V8.108c0-.27.173-.51.43-.595.06-.023.136-.033.194-.033.195 0 .375.104.495.254l2.462 3.33V8.108c0-.345.282-.63.63-.63.345 0 .63.285.63.63v4.771zm-5.741 0c0 .344-.282.629-.631.629-.345 0-.627-.285-.627-.629V8.108c0-.345.282-.63.63-.63.346 0 .628.285.628.63v4.771zm-2.466.629H4.917c-.345 0-.63-.285-.63-.629V8.108c0-.345.285-.63.63-.63.348 0 .63.285.63.63v4.141h1.756c.348 0 .629.283.629.63 0 .344-.281.629-.629.629M24 10.314C24 4.943 18.615.572 12 .572S0 4.943 0 10.314c0 4.811 4.27 8.842 10.035 9.608.391.082.923.258 1.058.59.12.301.079.766.038 1.08l-.164 1.02c-.045.301-.24 1.186 1.049.645 1.291-.539 6.916-4.070 9.436-6.975C23.176 14.393 24 12.458 24 10.314"/>
        </svg>
        {large ? "LINEでシェア" : "LINE"}
      </a>

      {/* Facebook */}
      <a
        href={`https://www.facebook.com/sharer/sharer.php?u=${encodedUrl}`}
        target="_blank"
        rel="noopener noreferrer"
        onClick={() => trackShare("Facebook", title)}
        className={`${btnClass} bg-[#1877F2] text-white`}
        aria-label="Facebookでシェア"
      >
        <svg className={large ? "w-4 h-4" : "w-3 h-3"} viewBox="0 0 24 24" fill="currentColor">
          <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/>
        </svg>
        {large ? "Facebookでシェア" : "FB"}
      </a>

      {/* URLコピー */}
      <button
        onClick={copyUrl}
        className={`${btnClass} ${copied ? "bg-green-500 text-white" : "bg-gray-100 text-gray-700 hover:bg-gray-200"}`}
        aria-label="URLをコピー"
      >
        {copied ? (
          <>
            <svg className={large ? "w-4 h-4" : "w-3 h-3"} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
            </svg>
            {large ? "コピーしました！" : "コピー完了"}
          </>
        ) : (
          <>
            <svg className={large ? "w-4 h-4" : "w-3 h-3"} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
            </svg>
            {large ? "URLをコピー" : "コピー"}
          </>
        )}
      </button>
    </div>
  );
}
