"use client";
/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI v2056.8
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * Redistribution / derivative-work / reverse-engineering prohibited
 * (著作権法 / 不正競争防止法 / 当社利用規約 第 8 条).
 * License inquiries: nomura.y@soloptilink.com
 * ----------------------------------------------------------------*/
import { useEffect, useState } from "react";

interface Heading {
  id: string;
  text: string;
  level: number;
}

export default function TableOfContents({ headings, variant = "inline" }: { headings: Heading[]; variant?: "inline" | "side" }) {
  const [open, setOpen] = useState(variant === "side");
  const [active, setActive] = useState<string | null>(null);
  const h2s = headings.filter((h) => h.level === 2);

  useEffect(() => {
    if (variant !== "side") return;
    const els = headings.filter((h) => h.level === 2).map((h) => document.getElementById(h.id)).filter((e): e is HTMLElement => Boolean(e));
    const io = new IntersectionObserver(
      (entries) => {
        const visible = entries.filter((e) => e.isIntersecting).sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top);
        if (visible[0]) setActive(visible[0].target.id);
      },
      { rootMargin: "-20% 0px -70% 0px" },
    );
    els.forEach((e) => io.observe(e));
    return () => io.disconnect();
  }, [variant, headings]);

  if (headings.length < 3) return null;

  if (variant === "side") {
    return (
      <nav aria-label="目次">
        <p className="section-rule kicker text-ink">Contents</p>
        <ol className="mt-4 space-y-3 border-l border-line">
          {h2s.map((h) => (
            <li key={h.id}>
              <a
                href={`#${h.id}`}
                className={`-ml-px block border-l-2 pl-4 text-[13px] leading-[1.6] transition-colors ${active === h.id ? "border-accent font-bold text-ink" : "border-transparent text-mute hover:text-ink"}`}
              >
                {h.text}
              </a>
            </li>
          ))}
        </ol>
      </nav>
    );
  }

  return (
    <nav aria-label="目次" className="mb-12 border border-line bg-white">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        aria-expanded={open}
        className="flex w-full items-center justify-between px-5 py-4 text-left"
      >
        <span className="flex items-baseline gap-3">
          <span className="text-[15px] font-bold">目次</span>
          <span className="kicker text-mute">Contents</span>
        </span>
        <span aria-hidden className={`text-accent transition-transform ${open ? "rotate-45" : ""}`}>＋</span>
      </button>
      {open && (
        <ol className="border-t border-line px-5 py-4">
          {h2s.map((h, i) => (
            <li key={h.id} className="py-1.5">
              <a href={`#${h.id}`} className="grid grid-cols-[28px_1fr] text-[14px] leading-[1.7] text-ink-soft hover:text-accent">
                <span className="font-[family-name:var(--font-latin)] font-semibold text-accent">{String(i + 1).padStart(2, "0")}</span>
                <span>{h.text}</span>
              </a>
            </li>
          ))}
        </ol>
      )}
    </nav>
  );
}
