"use client";
/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
import { useState } from "react";

interface Heading {
  id: string;
  text: string;
  level: number;
}

interface Props {
  headings: Heading[];
}

export default function TableOfContents({ headings }: Props) {
  const [open, setOpen] = useState(true);

  if (headings.length < 3) return null;

  return (
    <nav className="bg-gray-50 border border-gray-200 rounded-xl p-5 mb-8" aria-label="目次">
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center justify-between w-full font-bold text-gray-800 text-sm"
      >
        <span className="flex items-center gap-2">
          <svg className="w-4 h-4 text-purple-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M4 6h16M4 10h16M4 14h10" />
          </svg>
          目次
        </span>
        <svg
          className={`w-4 h-4 text-gray-400 transition-transform ${open ? "" : "-rotate-90"}`}
          fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}
        >
          <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
        </svg>
      </button>
      {open && (
        <ol className="mt-3 space-y-1.5">
          {headings.map((h, i) => (
            <li key={i} className={h.level === 3 ? "ml-4" : ""}>
              <a
                href={`#${h.id}`}
                className="text-sm text-purple-600 hover:text-purple-800 hover:underline flex items-start gap-1.5 group"
              >
                <span className="text-gray-400 text-xs mt-0.5 flex-shrink-0 font-mono">
                  {h.level === 2 ? `${headings.filter((x, j) => j <= i && x.level === 2).length}.` : "└"}
                </span>
                <span className="group-hover:underline leading-snug">{h.text}</span>
              </a>
            </li>
          ))}
        </ol>
      )}
    </nav>
  );
}
