/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI v2056.8
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * Redistribution / derivative-work / reverse-engineering prohibited
 * (著作権法 / 不正競争防止法 / 当社利用規約 第 8 条).
 * License inquiries: nomura.y@soloptilink.com
 * ----------------------------------------------------------------*/
import { Marked, type Tokens } from "marked";

const SUMMARY_RE = /^## (この記事でわかること[^\n]*|この記事でわかる[^\n]*|この記事のポイント[^\n]*)\n([\s\S]*?)(?=\n## |\s*$)/m;

export const headingId = (text: string) => encodeURIComponent(text.trim());

function createMarked() {
  const m = new Marked({ gfm: true, breaks: false });
  m.use({
    renderer: {
      heading(this: { parser: { parseInline: (t: Tokens.Heading["tokens"]) => string } }, token: Tokens.Heading) {
        const inner = this.parser.parseInline(token.tokens);
        const level = Math.min(Math.max(token.depth, 2), 4);
        return `<h${level} id="${headingId(token.text)}">${inner}</h${level}>\n`;
      },
      link(this: { parser: { parseInline: (t: Tokens.Link["tokens"]) => string } }, token: Tokens.Link) {
        const inner = this.parser.parseInline(token.tokens);
        const href = token.href || "#";
        const external = /^https?:\/\//.test(href) && !href.startsWith("https://media.seasonsezon.co.jp");
        return `<a href="${href}"${external ? ' target="_blank" rel="noopener noreferrer"' : ""}>${inner}</a>`;
      },
    },
  });
  return m;
}

const marked = createMarked();

export function extractHeadings(content: string): { id: string; text: string; level: number }[] {
  const body = stripLeadingTitle(content).replace(SUMMARY_RE, "");
  const out: { id: string; text: string; level: number }[] = [];
  for (const m of body.matchAll(/^(#{2,3}) (.+)$/gm)) {
    out.push({ id: headingId(m[2]), text: m[2].replace(/[*`]/g, "").trim(), level: m[1].length });
  }
  return out;
}

function stripLeadingTitle(content: string) {
  return content.replace(/^\s*# [^\n]+\n/, "");
}

const GENERIC = /^(ChatGPT|Claude|Gemini|Copilot|OpenAI|Google|Notion|Perplexity|Midjourney|生成AI|プロンプト|完全ガイド|徹底解説|使い方|活用法|活用術)$|^\d|年版|最新/;

/** 本文のキーワードに、関連記事への内部リンクを最大 limit 件まで張る（見出し・既存リンク内は対象外） */
function insertInternalLinks(html: string, targets: { slug: string; title: string }[], limit = 5) {
  const parts = html.split(/(<[^>]+>)/);
  let depthA = 0;
  let depthH = 0;
  let inserted = 0;
  const used = new Set<string>();
  const candidates = targets
    .map((t) => ({
      slug: t.slug,
      // 「ChatGPT」などの総称語にリンクを張ると無関係な記事へ飛ぶため、記事固有の語だけを使う
      kw: t.title.split(/[\s・｜|【】！？!?、。]/).find((w) => w.length >= 6 && !GENERIC.test(w)),
    }))
    .filter((c): c is { slug: string; kw: string } => Boolean(c.kw));

  return parts
    .map((part) => {
      if (part.startsWith("<")) {
        if (/^<a[\s>]/.test(part)) depthA++;
        else if (/^<\/a>/.test(part)) depthA--;
        else if (/^<h\d/.test(part)) depthH++;
        else if (/^<\/h\d/.test(part)) depthH--;
        return part;
      }
      if (depthA > 0 || depthH > 0 || inserted >= limit) return part;
      let text = part;
      for (const c of candidates) {
        if (inserted >= limit) break;
        if (used.has(c.slug)) continue;
        const idx = text.indexOf(c.kw);
        if (idx === -1) continue;
        text = `${text.slice(0, idx)}<a href="/articles/${c.slug}">${c.kw}</a>${text.slice(idx + c.kw.length)}`;
        used.add(c.slug);
        inserted++;
        break;
      }
      return text;
    })
    .join("");
}

export function renderArticle(content: string, linkTargets: { slug: string; title: string }[] = []): string {
  let body = stripLeadingTitle(content);
  let summary = "";
  const sm = body.match(SUMMARY_RE);
  if (sm) {
    summary = `<div class="summary-box"><h2>Point｜${sm[1]}</h2>${marked.parse(sm[2]) as string}</div>\n`;
    body = body.replace(SUMMARY_RE, "");
  }
  const html = (marked.parse(body) as string).replace(/<table>/g, '<div class="table-wrap"><table>').replace(/<\/table>/g, "</table></div>");
  return summary + insertInternalLinks(html, linkTargets);
}

export function extractFAQ(content: string): { q: string; a: string }[] {
  const faqs: { q: string; a: string }[] = [];
  const lines = content.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const h = lines[i].match(/^#{2,4} (.+)/);
    if (h && (h[1].includes("？") || h[1].includes("?") || /^Q[.:：\d]/.test(h[1]))) {
      const answer: string[] = [];
      for (let j = i + 1; j < lines.length && !/^#{1,4} /.test(lines[j]); j++) {
        if (lines[j].trim()) answer.push(lines[j].replace(/[*#`>]/g, "").trim());
      }
      if (answer.length) faqs.push({ q: h[1].replace(/[*`]/g, "").trim(), a: answer.join(" ").slice(0, 300) });
    }
  }
  return faqs.slice(0, 5);
}
