/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI v2056.8
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * Redistribution / derivative-work / reverse-engineering prohibited
 * (著作権法 / 不正競争防止法 / 当社利用規約 第 8 条).
 * License inquiries: nomura.y@soloptilink.com
 * ----------------------------------------------------------------*/
import { createHash } from "node:crypto";
import coverFiles from "./cover-manifest.json";

export const SITE_URL = "https://media.seasonsezon.co.jp";
export const SITE_NAME = "AI活用ラボ";
export const OPERATOR = {
  name: "株式会社セゾン",
  url: "https://seasonsezon.co.jp/",
  email: "info@seasonsezon.co.jp",
  summary: "SNS運用代行およびAIシステムの販売・導入支援",
};

export const CATEGORIES = [
  { slug: "chatgpt", name: "ChatGPT活用術", en: "ChatGPT", lead: "毎日の仕事にChatGPTを組み込むための、具体的な使い方と型。" },
  { slug: "ai-business", name: "AI業務効率化", en: "Business", lead: "現場の業務をAIでどう変えるか。導入手順と事例を追う。" },
  { slug: "ai-tools", name: "AIツール比較", en: "Tools", lead: "目的別に選ぶ、AIツールの実力と選び方。" },
  { slug: "prompt", name: "プロンプト技術", en: "Prompt", lead: "AIの出力を変える、指示の書き方と設計のコツ。" },
  { slug: "ai-income", name: "AI副業・収益化", en: "Side Business", lead: "AIを使って個人で稼ぐための現実的なロードマップ。" },
  { slug: "ai-news", name: "AI最新ニュース", en: "News", lead: "押さえておくべきAI業界の動きと、その読み解き方。" },
] as const;

export type CategorySlug = (typeof CATEGORIES)[number]["slug"];

export function categoryMeta(slug: string | null | undefined) {
  return CATEGORIES.find((c) => c.slug === slug) ?? null;
}

const available = new Set<string>(coverFiles as string[]);

export function hasOwnCover(slug: string): boolean {
  return available.has(`c-${createHash("sha1").update(slug).digest("hex").slice(0, 10)}`);
}

export function hasHero(): boolean {
  return available.has("hero-home");
}

/** 記事のアイキャッチ。記事専用の画像が無ければカテゴリ画像、それも無ければ共通画像を返す。 */
export function coverFor(slug: string, categorySlug?: string | null): string {
  const file = `c-${createHash("sha1").update(slug).digest("hex").slice(0, 10)}`;
  if (available.has(file)) return `/covers/${file}.webp`;
  if (categorySlug && available.has(`category-${categorySlug}`)) return `/covers/category-${categorySlug}.webp`;
  if (available.has("category-default")) return "/covers/category-default.webp";
  return "/covers/fallback.svg";
}

export function categoryCover(slug: string): string {
  if (available.has(`category-${slug}`)) return `/covers/category-${slug}.webp`;
  return available.has("category-default") ? "/covers/category-default.webp" : "/covers/fallback.svg";
}

export function heroCover(): string {
  return available.has("hero-home") ? "/covers/hero-home.webp" : categoryCover("default");
}

export function formatDateJa(date: Date | string | null | undefined): string {
  if (!date) return "";
  const d = new Date(date);
  return `${d.getFullYear()}.${String(d.getMonth() + 1).padStart(2, "0")}.${String(d.getDate()).padStart(2, "0")}`;
}
