/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * ----------------------------------------------------------------*/
import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .replace(/[\s_-]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function estimateReadingTime(content: string): number {
  const wordsPerMinute = 400;
  const words = content.split(/\s+/).length;
  return Math.ceil(words / wordsPerMinute);
}

export function formatDate(date: Date | string): string {
  return new Date(date).toLocaleDateString("ja-JP", {
    year: "numeric", month: "long", day: "numeric",
  });
}

export function formatNumber(n: number): string {
  return new Intl.NumberFormat("ja-JP").format(n);
}
