/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

const STATUS_LABEL: Record<string, { label: string; color: string }> = {
  published: { label: "公開中", color: "bg-emerald-100 text-emerald-700" },
  draft:     { label: "下書き", color: "bg-gray-100 text-gray-600" },
  scheduled: { label: "予約済み", color: "bg-blue-100 text-blue-700" },
};

export default function ArticlesPage() {
  const [articles, setArticles] = useState<any[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState("all");

  async function load(status?: string) {
    setLoading(true);
    const q = status && status !== "all" ? `?status=${status}` : "";
    const res = await fetch(`/api/articles${q}&limit=50`);
    const d = await res.json();
    setArticles(d.articles ?? []);
    setTotal(d.total ?? 0);
    setLoading(false);
  }

  useEffect(() => { load(); }, []);

  function changeFilter(f: string) {
    setFilter(f);
    load(f === "all" ? undefined : f);
  }

  async function deleteArticle(id: string) {
    if (!confirm("この記事を削除しますか？")) return;
    await fetch(`/api/articles/${id}`, { method: "DELETE" });
    setArticles(prev => prev.filter(a => a.id !== id));
  }

  async function togglePublish(article: any) {
    const newStatus = article.status === "published" ? "draft" : "published";
    await fetch(`/api/articles/${article.id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ status: newStatus }),
    });
    setArticles(prev => prev.map((a: any) => a.id === article.id ? { ...a, status: newStatus } : a));
  }

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">記事管理</h1>
          <p className="text-sm text-gray-500">全{total}件</p>
        </div>
        <div className="flex gap-3">
          <Link href="/admin/generate" className="bg-purple-600 hover:bg-purple-700 text-white text-sm px-4 py-2 rounded-lg font-medium">
            🤖 AI生成
          </Link>
          <Link href="/admin/articles/new" className="bg-white border border-gray-300 hover:border-gray-400 text-sm px-4 py-2 rounded-lg font-medium">
            ✏️ 手動作成
          </Link>
        </div>
      </div>

      {/* Filter tabs */}
      <div className="flex gap-2">
        {["all","published","draft","scheduled"].map((f: any) => (
          <button
            key={f}
            onClick={() => changeFilter(f)}
            className={`px-4 py-1.5 rounded-full text-sm font-medium transition-colors ${filter === f ? "bg-purple-600 text-white" : "bg-white border border-gray-200 text-gray-600 hover:border-purple-400"}`}
          >
            {{ all:"すべて", published:"公開中", draft:"下書き", scheduled:"予約済み" }[f]}
          </button>
        ))}
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        {loading ? (
          <div className="p-8 text-center text-gray-400">読み込み中...</div>
        ) : articles.length === 0 ? (
          <div className="p-12 text-center">
            <p className="text-gray-400 mb-4">記事がありません</p>
            <Link href="/admin/generate" className="text-purple-600 hover:underline text-sm">AI記事生成で記事を作成する →</Link>
          </div>
        ) : (
          <table className="w-full">
            <thead className="bg-gray-50 border-b border-gray-100">
              <tr>
                <th className="text-left text-xs font-semibold text-gray-500 px-4 py-3">タイトル</th>
                <th className="text-left text-xs font-semibold text-gray-500 px-4 py-3 w-28">カテゴリ</th>
                <th className="text-left text-xs font-semibold text-gray-500 px-4 py-3 w-20">ステータス</th>
                <th className="text-right text-xs font-semibold text-gray-500 px-4 py-3 w-16">PV</th>
                <th className="text-left text-xs font-semibold text-gray-500 px-4 py-3 w-24">作成日</th>
                <th className="text-right text-xs font-semibold text-gray-500 px-4 py-3 w-36">操作</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {articles.map((article: any) => {
                const s = STATUS_LABEL[article.status] ?? STATUS_LABEL.draft;
                return (
                  <tr key={article.id} className="hover:bg-gray-50 transition-colors">
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-2">
                        {article.aiGenerated && <span className="text-xs bg-purple-100 text-purple-600 px-1.5 py-0.5 rounded font-medium">AI</span>}
                        <Link href={`/admin/articles/${article.id}`} className="text-sm text-gray-800 hover:text-purple-600 font-medium line-clamp-1">
                          {article.title}
                        </Link>
                      </div>
                    </td>
                    <td className="px-4 py-3">
                      <span className="text-xs text-gray-500">{article.category?.name ?? "—"}</span>
                    </td>
                    <td className="px-4 py-3">
                      <span className={`text-xs px-2 py-1 rounded-full font-medium ${s.color}`}>{s.label}</span>
                    </td>
                    <td className="px-4 py-3 text-right">
                      <span className="text-sm font-medium text-gray-700">{(article._count?.views ?? 0).toLocaleString()}</span>
                    </td>
                    <td className="px-4 py-3">
                      <span className="text-xs text-gray-400">{new Date(article.createdAt).toLocaleDateString("ja-JP")}</span>
                    </td>
                    <td className="px-4 py-3 text-right">
                      <div className="flex items-center justify-end gap-2">
                        <button onClick={() => togglePublish(article)} className={`text-xs px-2 py-1 rounded border transition-colors ${article.status === "published" ? "border-gray-300 text-gray-600 hover:border-red-300 hover:text-red-600" : "border-emerald-300 text-emerald-600 hover:bg-emerald-50"}`}>
                          {article.status === "published" ? "下書きへ" : "公開する"}
                        </button>
                        <Link href={`/admin/articles/${article.id}`} className="text-xs px-2 py-1 rounded border border-purple-200 text-purple-600 hover:bg-purple-50">編集</Link>
                        <button onClick={() => deleteArticle(article.id)} className="text-xs px-2 py-1 rounded border border-red-200 text-red-500 hover:bg-red-50">削除</button>
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
