/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { formatDate } from "@/lib/utils";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "記事検索 | AI活用ラボ",
  description: "AI活用ラボの記事を検索できます。ChatGPT・Claude・Geminiの使い方、副業、業務効率化など。",
  robots: { index: false, follow: true },
};

const CATEGORY_COLORS: Record<string, string> = {
  chatgpt: "bg-emerald-100 text-emerald-700",
  "ai-business": "bg-purple-100 text-purple-700",
  "ai-tools": "bg-amber-100 text-amber-700",
  prompt: "bg-red-100 text-red-700",
  "ai-income": "bg-violet-100 text-violet-700",
  "ai-news": "bg-cyan-100 text-cyan-700",
};

export default async function SearchPage({
  searchParams,
}: {
  searchParams: Promise<{ q?: string }>;
}) {
  const { q } = await searchParams;
  const query = q?.trim() || "";

  const articles = query
    ? await prisma.article.findMany({
        where: {
          status: "published",
          OR: [
            { title: { contains: query } },
            { excerpt: { contains: query } },
            { seoKeywords: { contains: query } },
          ],
        },
        include: { category: true, _count: { select: { views: true } } },
        orderBy: { publishedAt: "desc" },
        take: 30,
      })
    : [];

  return (
    <main className="max-w-4xl mx-auto px-4 py-10">
      <nav className="flex items-center gap-2 text-sm text-gray-400 mb-6">
        <Link href="/" className="hover:text-purple-600">ホーム</Link>
        <span>/</span>
        <span className="text-gray-700">記事検索</span>
      </nav>

      <h1 className="text-2xl font-bold text-gray-900 mb-6">🔍 記事を検索する</h1>

      {/* 検索フォーム */}
      <form method="get" action="/search" className="mb-8">
        <div className="flex gap-3">
          <input
            type="text"
            name="q"
            defaultValue={query}
            placeholder="キーワードを入力（例: ChatGPT, プロンプト, 副業...）"
            className="flex-1 border border-gray-200 rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-purple-400"
            autoFocus
          />
          <button type="submit"
            className="bg-purple-600 text-white px-6 py-3 rounded-xl font-medium hover:bg-purple-700 transition-colors text-sm">
            検索
          </button>
        </div>
      </form>

      {/* 検索結果 */}
      {query && (
        <>
          <p className="text-sm text-gray-500 mb-4">
            「<strong className="text-gray-800">{query}</strong>」の検索結果: {articles.length}件
          </p>
          {articles.length === 0 ? (
            <div className="text-center py-16 text-gray-400">
              <p className="text-3xl mb-4">🔍</p>
              <p>「{query}」に一致する記事が見つかりませんでした</p>
              <Link href="/articles" className="mt-4 inline-block text-purple-600 hover:underline text-sm">
                すべての記事を見る →
              </Link>
            </div>
          ) : (
            <div className="space-y-4">
              {articles.map((article: any) => (
                <Link key={article.id} href={`/articles/${article.slug}`}
                  className="flex gap-4 bg-white rounded-xl border border-gray-100 p-4 hover:shadow-md transition-shadow group">
                  <div className="w-16 h-16 flex-shrink-0 bg-gradient-to-br from-purple-100 to-indigo-100 rounded-lg flex items-center justify-center text-2xl">
                    🤖
                  </div>
                  <div className="flex-1 min-w-0">
                    <h2 className="font-bold text-gray-900 group-hover:text-purple-600 transition-colors line-clamp-1 mb-1">{article.title}</h2>
                    <p className="text-sm text-gray-500 line-clamp-2">{article.excerpt}</p>
                    <div className="flex items-center gap-3 mt-2">
                      {article.category && (
                        <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${CATEGORY_COLORS[article.category.slug] || "bg-gray-100 text-gray-600"}`}>
                          {article.category.name}
                        </span>
                      )}
                      <span className="text-xs text-gray-400">{formatDate(article.publishedAt || article.createdAt)}</span>
                    </div>
                  </div>
                </Link>
              ))}
            </div>
          )}
        </>
      )}

      {!query && (
        <div className="text-center py-10 text-gray-400">
          <p className="text-4xl mb-3">🔍</p>
          <p>検索したいキーワードを入力してください</p>
          <div className="flex flex-wrap justify-center gap-2 mt-6">
            {["ChatGPT", "プロンプト", "AI副業", "業務効率化", "Gemini", "Claude"].map(kw => (
              <a key={kw} href={`/search?q=${encodeURIComponent(kw)}`}
                className="text-sm bg-purple-50 text-purple-700 px-4 py-2 rounded-full hover:bg-purple-100 transition-colors">
                {kw}
              </a>
            ))}
          </div>
        </div>
      )}
    </main>
  );
}
