/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI v2056.8
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * Redistribution / derivative-work / reverse-engineering prohibited
 * (著作権法 / 不正競争防止法 / 当社利用規約 第 8 条).
 * License inquiries: nomura.y@soloptilink.com
 * ----------------------------------------------------------------*/
import Link from "next/link";
import type { Metadata } from "next";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import ArticleCard, { type CardArticle } from "@/components/media/ArticleCard";

export const metadata: Metadata = {
  title: "記事を検索",
  robots: { index: false, follow: true },
  openGraph: { url: "https://media.seasonsezon.co.jp/search" },
};

const querySchema = z.string().trim().max(60).catch("");
const SUGGESTIONS = ["ChatGPT 使い方", "プロンプト", "議事録", "Claude", "Gemini", "副業", "画像生成", "Copilot"];

export default async function SearchPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const { q } = await searchParams;
  const query = querySchema.parse(q ?? "");

  let articles: CardArticle[] = [];
  let failed = false;
  if (query) {
    try {
      articles = (await prisma.article.findMany({
        where: {
          status: "published",
          OR: [{ title: { contains: query } }, { excerpt: { contains: query } }, { seoKeywords: { contains: query } }],
        },
        select: { id: true, slug: true, title: true, excerpt: true, publishedAt: true, createdAt: true, readingTime: true, category: { select: { slug: true, name: true } } },
        orderBy: { publishedAt: "desc" },
        take: 30,
      })) as CardArticle[];
    } catch {
      failed = true;
    }
  }

  return (
    <main className="mx-auto max-w-[1000px] px-5 pt-12 md:px-6 md:pt-16">
      <p className="kicker text-accent-deep">Search</p>
      <h1 className="mt-2 text-[28px] font-black tracking-[0.04em] md:text-[36px]">記事を検索</h1>

      <form method="get" action="/search" className="mt-8 flex border-b-2 border-ink focus-within:border-accent-deep" role="search">
        <label htmlFor="q" className="sr-only">キーワード</label>
        <input
          id="q"
          name="q"
          type="search"
          defaultValue={query}
          maxLength={60}
          placeholder="キーワードを入力（例：議事録、プロンプト）"
          className="min-w-0 flex-1 bg-transparent py-4 text-[17px] outline-none placeholder:text-mute"
        />
        <button type="submit" className="bg-ink px-6 text-[14px] font-bold text-white hover:bg-accent">検索</button>
      </form>

      <div className="mt-5 flex flex-wrap gap-2">
        {SUGGESTIONS.map((s) => (
          <Link key={s} href={`/search?q=${encodeURIComponent(s)}`} className="border border-line px-3 py-1.5 text-[12px] text-ink-soft hover:border-ink hover:text-ink">
            {s}
          </Link>
        ))}
      </div>

      <div className="mt-14">
        {failed ? (
          <p className="py-16 text-center text-mute">検索中に問題が起きました。時間をおいてもう一度お試しください。</p>
        ) : query && articles.length === 0 ? (
          <p className="py-16 text-center text-mute">「{query}」に一致する記事は見つかりませんでした。別の言葉でお試しください。</p>
        ) : query ? (
          <>
            <p className="mb-8 text-[13px] text-mute">「{query}」の検索結果：{articles.length}件</p>
            <ul className="space-y-10">
              {articles.map((a) => (
                <li key={a.id}>
                  <ArticleCard a={a} variant="row" />
                </li>
              ))}
            </ul>
          </>
        ) : null}
      </div>
    </main>
  );
}
