/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import {
  LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid,
  Tooltip, ResponsiveContainer, PieChart, Pie, Cell
} from "recharts";

const COLORS = ["#8b5cf6","#10b981","#f59e0b","#ef4444","#06b6d4"];

function StatCard({ label, value, sub, color }: { label: string; value: string | number; sub?: string; color?: string }) {
  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-5">
      <p className="text-xs text-gray-500 font-medium uppercase tracking-wide">{label}</p>
      <p className={`text-3xl font-bold mt-1 ${color || "text-gray-900"}`}>{value}</p>
      {sub && <p className="text-xs text-gray-400 mt-1">{sub}</p>}
    </div>
  );
}

export default function DashboardPage() {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/analytics?days=30")
      .then(r => r.json())
      .then(d => { setData(d); setLoading(false); })
      .catch(() => setLoading(false));
  }, []);

  if (loading) return (
    <div className="space-y-5">
      <div className="h-8 bg-gray-200 rounded animate-pulse w-48" />
      <div className="grid grid-cols-4 gap-4">
        {[...Array(4)].map((_, i) => <div key={i} className="h-28 bg-gray-200 rounded-xl animate-pulse" />)}
      </div>
    </div>
  );

  const ov = data?.overview ?? {};
  const pvGoal = 100000;
  const pvProgress = Math.min(100, Math.round((ov.projectedMonthlyPV || 0) / pvGoal * 100));

  const pvData = (data?.viewsByDay ?? []).map((r: any) => ({
    date: String(r.date).slice(5),
    PV: Number(r.count),
  }));

  const revData: Record<string, any> = {};
  (data?.revenueByDay ?? []).forEach((r: any) => {
    const d = String(r.date).slice(5);
    if (!revData[d]) revData[d] = { date: d };
    revData[d][r.type] = Number(r.total);
  });
  const revenueChart = Object.values(revData).slice(-14);

  const pieData = [
    { name: "AdSense", value: 45 },
    { name: "アフィリエイト", value: 30 },
    { name: "スポンサー", value: 15 },
    { name: "問い合わせ", value: 10 },
  ];

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">ダッシュボード</h1>
          <p className="text-sm text-gray-500 mt-0.5">AIメディア運営の全体状況</p>
        </div>
        <div className="flex gap-3">
          <Link href="/admin/generate" className="bg-purple-600 hover:bg-purple-700 text-white text-sm px-4 py-2 rounded-lg font-medium transition-colors">
            🤖 AI記事生成
          </Link>
          <Link href="/admin/articles/new" className="bg-white border border-gray-300 hover:border-gray-400 text-sm px-4 py-2 rounded-lg font-medium transition-colors">
            ✏️ 記事作成
          </Link>
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <StatCard label="月間PV（推計）" value={`${(ov.projectedMonthlyPV || 0).toLocaleString()}`} sub={`目標: 100,000 PV`} color="text-purple-600" />
        <StatCard label="本日のPV" value={(ov.todayViews || 0).toLocaleString()} sub="今日の閲覧数" />
        <StatCard label="月間収益" value={`¥${Math.round(ov.monthlyRevenue || 0).toLocaleString()}`} sub="直近30日合計" color="text-emerald-600" />
        <StatCard label="公開記事数" value={ov.publishedArticles || 0} sub={`下書き: ${ov.draftArticles || 0}件`} />
      </div>

      {/* PV目標達成率 */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-5">
        <div className="flex items-center justify-between mb-3">
          <h2 className="font-semibold text-gray-800">月間PV目標達成率</h2>
          <span className="text-sm font-bold text-purple-600">{pvProgress}%</span>
        </div>
        <div className="w-full bg-gray-100 rounded-full h-4">
          <div
            className="bg-gradient-to-r from-purple-500 to-indigo-500 h-4 rounded-full transition-all duration-500"
            style={{ width: `${pvProgress}%` }}
          />
        </div>
        <div className="flex justify-between text-xs text-gray-400 mt-2">
          <span>現在: {(ov.projectedMonthlyPV || 0).toLocaleString()} PV</span>
          <span>目標: 100,000 PV</span>
        </div>
      </div>

      {/* Charts */}
      <div className="grid grid-cols-3 gap-4">
        {/* PV推移 */}
        <div className="col-span-2 bg-white rounded-xl shadow-sm border border-gray-100 p-5">
          <h2 className="font-semibold text-gray-800 mb-4">PV推移（直近30日）</h2>
          {pvData.length > 0 ? (
            <ResponsiveContainer width="100%" height={220}>
              <LineChart data={pvData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
                <XAxis dataKey="date" tick={{ fontSize: 11 }} />
                <YAxis tick={{ fontSize: 11 }} />
                <Tooltip />
                <Line type="monotone" dataKey="PV" stroke="#8b5cf6" strokeWidth={2} dot={false} />
              </LineChart>
            </ResponsiveContainer>
          ) : <div className="h-[220px] flex items-center justify-center text-gray-400 text-sm">データ収集中...</div>}
        </div>

        {/* 収益構成 */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-5">
          <h2 className="font-semibold text-gray-800 mb-4">収益構成</h2>
          <ResponsiveContainer width="100%" height={180}>
            <PieChart>
              <Pie data={pieData} cx="50%" cy="50%" outerRadius={70} dataKey="value" label={({ name, percent }: any) => `${name ?? ""} ${(((percent ?? 0)*100)).toFixed(0)}%`} labelLine={false}>
                {pieData.map((_, i) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}
              </Pie>
              <Tooltip />
            </PieChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* 収益推移 */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-5">
        <h2 className="font-semibold text-gray-800 mb-4">収益推移（直近14日）</h2>
        {revenueChart.length > 0 ? (
          <ResponsiveContainer width="100%" height={200}>
            <BarChart data={revenueChart}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
              <XAxis dataKey="date" tick={{ fontSize: 11 }} />
              <YAxis tick={{ fontSize: 11 }} tickFormatter={v => `¥${v.toLocaleString()}`} />
              <Tooltip formatter={(v: any) => `¥${Number(v).toLocaleString()}`} />
              <Bar dataKey="adsense" stackId="a" fill="#8b5cf6" name="AdSense" />
              <Bar dataKey="affiliate" stackId="a" fill="#10b981" name="アフィリエイト" />
              <Bar dataKey="inquiry" stackId="a" fill="#f59e0b" name="問い合わせ" />
            </BarChart>
          </ResponsiveContainer>
        ) : <div className="h-[200px] flex items-center justify-center text-gray-400 text-sm">データ収集中...</div>}
      </div>

      {/* Top記事 */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-5">
        <div className="flex items-center justify-between mb-4">
          <h2 className="font-semibold text-gray-800">人気記事 TOP10</h2>
          <Link href="/admin/articles" className="text-purple-600 text-sm hover:underline">すべて見る →</Link>
        </div>
        <div className="space-y-2">
          {(data?.topArticles ?? []).length === 0 ? (
            <p className="text-gray-400 text-sm text-center py-8">記事がありません。AI記事生成で記事を作成しましょう。</p>
          ) : (
            (data?.topArticles ?? []).map((article: any, i: number) => (
              <div key={article.id} className="flex items-center gap-3 py-2 border-b border-gray-50 last:border-0">
                <span className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold ${i < 3 ? "bg-purple-100 text-purple-700" : "bg-gray-100 text-gray-500"}`}>{i + 1}</span>
                <div className="flex-1 min-w-0">
                  <Link href={`/admin/articles/${article.id}`} className="text-sm text-gray-800 hover:text-purple-600 font-medium truncate block">{article.title}</Link>
                  <span className="text-xs text-gray-400">{article.category?.name}</span>
                </div>
                <div className="text-right">
                  <div className="text-sm font-semibold text-gray-900">{(article._count?.views || 0).toLocaleString()} PV</div>
                </div>
              </div>
            ))
          )}
        </div>
      </div>

      {/* Quick actions */}
      <div className="bg-gradient-to-r from-purple-600 to-indigo-600 rounded-xl p-5 text-white">
        <h2 className="font-semibold mb-3">🚀 次のアクション</h2>
        <div className="grid grid-cols-3 gap-3">
          <Link href="/admin/generate" className="bg-white/10 hover:bg-white/20 rounded-lg p-3 text-center text-sm transition-colors">
            🤖<br />AI記事を生成する
          </Link>
          <Link href="/admin/keywords" className="bg-white/10 hover:bg-white/20 rounded-lg p-3 text-center text-sm transition-colors">
            🔍<br />キーワードを追加する
          </Link>
          <Link href="/admin/revenue" className="bg-white/10 hover:bg-white/20 rounded-lg p-3 text-center text-sm transition-colors">
            💴<br />収益を記録する
          </Link>
        </div>
      </div>
    </div>
  );
}
