/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * ----------------------------------------------------------------*/
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import Anthropic from "@anthropic-ai/sdk";
import { slugify, estimateReadingTime } from "@/lib/utils";

export async function POST(req: NextRequest) {
  const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  try {
    const { keyword, keywordId, categoryId, autoPublish } = await req.json();
    if (!keyword) return NextResponse.json({ error: "キーワードが必要です" }, { status: 400 });

    const job = await prisma.generationJob.create({
      data: { keyword, keywordId, status: "running" },
    });

    const prompt = `あなたはAI活用・業務効率化専門のトップSEOライターです。
以下のキーワードで、Google検索1位・AIオーバービュー（AIO）掲載・月間5万PV以上を目指す超高品質な記事を執筆してください。

キーワード: ${keyword}

【必須構成】以下の構成を厳守してください:
1. タイトル（60文字以内・数字や「方法」「コツ」「完全ガイド」などを含む）
2. リード文（検索意図に直接回答・200文字以内）
3. ## この記事でわかること（箇条書き3〜5項目）
4. ## [キーワードの基本解説]（H2）
5. ## [具体的な使い方・手順]（H2）- 手順は番号付きリストで
6. ## [実践的な活用事例・Tips]（H2）
7. ## [よくある質問]（H2）- 以下形式で3〜5問
   ### [質問文]？
   [回答文 100〜200文字]
8. ## まとめ（H2）- 要点の箇条書き + 次のアクション提案

【SEO・AIO対応の要件】
- 文字数: 3000〜4000文字（充実した内容）
- キーワード密度: タイトル・H2・リード文・まとめに必ず含める
- E-E-A-T: 具体的な数字・事例・根拠を必ず入れる
- AIO対応: 質問と回答形式のFAQセクションを必ず含める（Googleが引用しやすい形式）
- 内部リンク用語: 関連キーワードを太字（**太字**）で自然に使う
- モバイル配慮: 短い段落（3〜4行以内）で読みやすく
- 読者: AIツールに興味があるビジネスパーソン・副業希望者・経営者
- トーン: わかりやすく・実践的・信頼性高く・背中を押す言葉で締める

以下のJSON形式のみで回答（JSON以外の文字は一切不要）:
{
  "title": "記事タイトル（60文字以内・数字を含む・クリックしたくなる）",
  "excerpt": "記事の要約（検索意図に直接回答・120文字以内）",
  "content": "本文（Markdown形式・3000〜4000文字・上記構成を厳守）",
  "seoTitle": "SEOタイトル（60文字以内・キーワード冒頭）",
  "seoDescription": "メタディスクリプション（120文字以内・CTAを含む）",
  "seoKeywords": "メインキーワード,関連KW1,関連KW2,関連KW3,関連KW4"
}`;

    let result: any;
    try {
      const response = await client.messages.create({
        model: "claude-sonnet-4-6",
        max_tokens: 8192,
        messages: [{ role: "user", content: prompt }],
      });
      const text = response.content[0].type === "text" ? response.content[0].text : "";
      const jsonMatch = text.match(/\{[\s\S]*\}/);
      if (!jsonMatch) throw new Error("JSONが見つかりません");
      result = JSON.parse(jsonMatch[0]);
    } catch (e: any) {
      await prisma.generationJob.update({
        where: { id: job.id },
        data: { status: "failed", errorMsg: e.message },
      });
      return NextResponse.json({ error: "AI生成失敗: " + e.message }, { status: 500 });
    }

    const slug = slugify(result.title) + "-" + Date.now().toString(36);
    const wordCount = result.content.split(/\s+/).length;
    const readingTime = estimateReadingTime(result.content);

    const article = await prisma.article.create({
      data: {
        title: result.title,
        slug,
        excerpt: result.excerpt,
        content: result.content,
        seoTitle: result.seoTitle,
        seoDescription: result.seoDescription,
        seoKeywords: result.seoKeywords,
        wordCount,
        readingTime,
        aiGenerated: true,
        keywordId: keywordId || null,
        categoryId: categoryId || null,
        status: autoPublish ? "published" : "draft",
        publishedAt: autoPublish ? new Date() : null,
      },
    });

    if (keywordId) {
      await prisma.keyword.update({
        where: { id: keywordId },
        data: { status: "published" },
      });
    }

    await prisma.generationJob.update({
      where: { id: job.id },
      data: { status: "completed", articleId: article.id, result: result.title },
    });

    return NextResponse.json({ article, job });
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}

export async function GET() {
  const jobs = await prisma.generationJob.findMany({
    orderBy: { createdAt: "desc" },
    take: 20,
  });
  return NextResponse.json(jobs);
}
