/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * ----------------------------------------------------------------*/
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import Anthropic from "@anthropic-ai/sdk";
import { slugify, estimateReadingTime } from "@/lib/utils";

export async function POST(req: NextRequest) {
  const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  try {
    const { keyword, keywordId, categoryId, autoPublish } = await req.json();
    if (!keyword) return NextResponse.json({ error: "キーワードが必要です" }, { status: 400 });

    const job = await prisma.generationJob.create({
      data: { keyword, keywordId, status: "running" },
    });

    const prompt = `あなたはAI活用・業務効率化専門のSEOライターです。
以下のキーワードで、月間10万PV以上を目指す高品質なブログ記事を執筆してください。

キーワード: ${keyword}

要件:
- 文字数: 2000〜3000文字
- 構成: 見出し（H2・H3）を使った読みやすい構成
- SEO: キーワードを自然に本文に組み込む
- 内容: 具体的な使い方・事例・メリット・デメリットを含む
- 読者: AIツールに興味があるビジネスパーソン・副業希望者
- トーン: わかりやすく・実践的に・信頼性高く

以下のJSON形式で回答してください:
{
  "title": "記事タイトル（60文字以内・検索意図に合致）",
  "excerpt": "記事の要約（120文字以内）",
  "content": "本文（Markdown形式・2000〜3000文字）",
  "seoTitle": "SEOタイトル（60文字以内）",
  "seoDescription": "メタディスクリプション（120文字以内）",
  "seoKeywords": "キーワード1,キーワード2,キーワード3"
}`;

    let result: any;
    try {
      const response = await client.messages.create({
        model: "claude-sonnet-4-6",
        max_tokens: 8192,
        messages: [{ role: "user", content: prompt }],
      });
      const text = response.content[0].type === "text" ? response.content[0].text : "";
      const jsonMatch = text.match(/\{[\s\S]*\}/);
      if (!jsonMatch) throw new Error("JSONが見つかりません");
      result = JSON.parse(jsonMatch[0]);
    } catch (e: any) {
      await prisma.generationJob.update({
        where: { id: job.id },
        data: { status: "failed", errorMsg: e.message },
      });
      return NextResponse.json({ error: "AI生成失敗: " + e.message }, { status: 500 });
    }

    const slug = slugify(result.title) + "-" + Date.now().toString(36);
    const wordCount = result.content.split(/\s+/).length;
    const readingTime = estimateReadingTime(result.content);

    const article = await prisma.article.create({
      data: {
        title: result.title,
        slug,
        excerpt: result.excerpt,
        content: result.content,
        seoTitle: result.seoTitle,
        seoDescription: result.seoDescription,
        seoKeywords: result.seoKeywords,
        wordCount,
        readingTime,
        aiGenerated: true,
        keywordId: keywordId || null,
        categoryId: categoryId || null,
        status: autoPublish ? "published" : "draft",
        publishedAt: autoPublish ? new Date() : null,
      },
    });

    if (keywordId) {
      await prisma.keyword.update({
        where: { id: keywordId },
        data: { status: "published" },
      });
    }

    await prisma.generationJob.update({
      where: { id: job.id },
      data: { status: "completed", articleId: article.id, result: result.title },
    });

    return NextResponse.json({ article, job });
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}

export async function GET() {
  const jobs = await prisma.generationJob.findMany({
    orderBy: { createdAt: "desc" },
    take: 20,
  });
  return NextResponse.json(jobs);
}
