/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import Anthropic from "@anthropic-ai/sdk";

export const maxDuration = 300; // 5分タイムアウト

const client = new Anthropic();

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .replace(/[\s]+/g, "-")
    .replace(/-+/g, "-")
    .slice(0, 60)
    .replace(/^-|-$/g, "");
}

async function generateArticle(keyword: string) {
  const response = await client.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 8192,
    messages: [
      {
        role: "user",
        content: `あなたはAI活用・業務効率化専門のトップSEOライターです。
以下のキーワードで、Google検索1位・AIオーバービュー（AIO）掲載・月間5万PV以上を目指す超高品質な記事を執筆してください。

キーワード: ${keyword}

【必須構成】
1. ## この記事でわかること（箇条書き3〜5項目）
2. ## ${keyword}とは（基本解説・定義）
3. ## 具体的な使い方・手順（番号付きリスト）
4. ## 実践的な活用事例・おすすめポイント
5. ## よくある質問（FAQ）
   ### [質問1]？
   [回答100〜200文字]
   ### [質問2]？
   [回答100〜200文字]
   ### [質問3]？
   [回答100〜200文字]
6. ## まとめ（要点箇条書き＋次のアクション）

【要件】
- 文字数: 3000〜4000文字
- キーワードをタイトル・H2・リード文・まとめに必ず含める
- 具体的な数字・事例・手順を入れる
- FAQ必須（Googleがスニペット・AIOで引用しやすい形式）
- 読者: AIに興味があるビジネスパーソン・副業希望者

以下のJSON形式のみで回答してください（JSON以外のテキストは含めないこと）:
{"title":"記事タイトル（60文字以内・数字含む）","excerpt":"要約（120文字以内・検索意図に直接回答）","content":"本文（Markdown・3000〜4000文字・上記構成厳守）","seoTitle":"SEOタイトル（60文字以内）","seoDescription":"メタディスクリプション（120文字以内・CTAあり）","seoKeywords":"${keyword},AI活用,ChatGPT,業務効率化"}`,
      },
    ],
  });

  const text = response.content[0].type === "text" ? response.content[0].text : "";
  const match = text.match(/\{[\s\S]*\}/);
  if (!match) throw new Error("JSON not found in response");
  return JSON.parse(match[0]);
}

export async function GET(req: NextRequest) {
  // Vercel Cron認証チェック
  const authHeader = req.headers.get("authorization");
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}` && process.env.NODE_ENV === "production") {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    // 記事のないキーワードを最大3件取得
    const allKeywords = await prisma.keyword.findMany({
      orderBy: { searchVolume: "desc" },
    });

    const existingTitles = await prisma.article.findMany({
      where: { status: "published" },
      select: { seoKeywords: true, title: true },
    });

    const usedKeywords = new Set(
      existingTitles.flatMap(a => (a.seoKeywords || "").split(",").map((k: string) => k.trim()))
    );

    const pending = allKeywords.filter(k => !usedKeywords.has(k.keyword)).slice(0, 3);

    if (pending.length === 0) {
      return NextResponse.json({ message: "全キーワードの記事が作成済みです", generated: 0 });
    }

    const CATEGORY_IDS: Record<string, string> = {
      "ChatGPT活用術": "cmrg33bif0001o3h1ok0jshe7",
      "AI業務効率化": "cmrg33big0002o3h1wgu0w6t0",
      "AIツール比較": "cmrg33big0003o3h1kvoj5tvo",
      "プロンプト技術": "cmrg33bih0004o3h1uojawgzu",
      "プロンプトエンジニアリング": "cmrg33bih0004o3h1uojawgzu",
      "AI副業・収益化": "cmrg33bii0005o3h1do852gfy",
      "AI最新ニュース": "cmrg33bii0006o3h1ntmi7odd",
    };

    const generated: string[] = [];
    for (const kw of pending) {
      try {
        const result = await generateArticle(kw.keyword);
        const now = new Date();
        const slug = slugify(result.title) + "-" + Date.now().toString(36);

        await prisma.article.create({
          data: {
            id: "cron" + Date.now().toString(36) + Math.random().toString(36).slice(2, 6),
            title: result.title,
            slug,
            excerpt: result.excerpt,
            content: result.content,
            seoTitle: result.seoTitle,
            seoDescription: result.seoDescription,
            seoKeywords: result.seoKeywords,
            wordCount: result.content.length,
            readingTime: Math.max(1, Math.floor(result.content.length / 400)),
            aiGenerated: true,
            categoryId: CATEGORY_IDS[kw.category] || "cmrg33bif0001o3h1ok0jshe7",
            status: "published",
            publishedAt: now,
          },
        });
        generated.push(result.title);
      } catch (e) {
        console.error(`生成失敗: ${kw.keyword}`, e);
      }
    }

    return NextResponse.json({
      message: `${generated.length}件の記事を生成しました`,
      generated,
      timestamp: new Date().toISOString(),
    });
  } catch (e) {
    console.error("Cron error:", e);
    return NextResponse.json({ error: "生成失敗" }, { status: 500 });
  }
}
