/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * ----------------------------------------------------------------*/
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { z } from "zod";

const KeywordSchema = z.object({
  keyword: z.string().min(1),
  searchVolume: z.number().min(0).default(0),
  difficulty: z.number().min(0).max(100).default(50),
  priority: z.enum(["high", "medium", "low"]).default("medium"),
  category: z.string().optional(),
});

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const status = searchParams.get("status");
  const priority = searchParams.get("priority");
  const where: any = {};
  if (status) where.status = status;
  if (priority) where.priority = priority;

  const keywords = await prisma.keyword.findMany({
    where,
    include: { _count: { select: { articles: true } } },
    orderBy: [{ priority: "asc" }, { searchVolume: "desc" }],
  });
  return NextResponse.json(keywords);
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const data = KeywordSchema.parse(body);
    const kw = await prisma.keyword.create({ data });
    return NextResponse.json(kw, { status: 201 });
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 400 });
  }
}
