/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
"use client";
import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";

export default function NewArticlePage() {
  const router = useRouter();
  const [categories, setCategories] = useState<any[]>([]);
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({
    title: "", excerpt: "", content: "", categoryId: "",
    status: "draft", seoTitle: "", seoDescription: "", seoKeywords: "",
  });

  useEffect(() => {
    fetch("/api/articles?limit=1").then(() => {});
    // カテゴリ取得
    fetch("/api/analytics?days=1").then(r => r.json()).then(() => {});
    fetch("/api/affiliates").then(r => r.json()).then(() => {});
  }, []);

  async function handleSave(status: string) {
    setSaving(true);
    try {
      const res = await fetch("/api/articles", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ ...form, status }),
      });
      if (res.ok) {
        const data = await res.json();
        router.push(`/admin/articles/${data.id}`);
      }
    } finally {
      setSaving(false);
    }
  }

  const wordCount = form.content.split(/\S+/).length - 1;

  return (
    <div className="max-w-4xl space-y-5">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-gray-900">新規記事作成</h1>
        <div className="flex gap-3">
          <button onClick={() => handleSave("draft")} disabled={saving || !form.title} className="border border-gray-300 hover:border-gray-400 text-sm px-4 py-2 rounded-lg font-medium disabled:opacity-40">
            下書き保存
          </button>
          <button onClick={() => handleSave("published")} disabled={saving || !form.title || !form.content} className="bg-purple-600 hover:bg-purple-700 text-white text-sm px-4 py-2 rounded-lg font-medium disabled:opacity-40">
            {saving ? "保存中..." : "公開する"}
          </button>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-5">
        <div className="col-span-2 space-y-4">
          <div className="bg-white rounded-xl border border-gray-100 p-5 space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">タイトル <span className="text-red-500">*</span></label>
              <input value={form.title} onChange={e => setForm(f => ({...f, title: e.target.value}))}
                className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none"
                placeholder="記事タイトルを入力" />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">要約</label>
              <textarea value={form.excerpt} onChange={e => setForm(f => ({...f, excerpt: e.target.value}))}
                rows={2} className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none resize-none"
                placeholder="記事の要約（120文字程度）" />
            </div>
            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="block text-sm font-medium text-gray-700">本文 <span className="text-red-500">*</span></label>
                <span className="text-xs text-gray-400">{wordCount.toLocaleString()} 文字</span>
              </div>
              <textarea value={form.content} onChange={e => setForm(f => ({...f, content: e.target.value}))}
                rows={20} className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none resize-y font-mono"
                placeholder="Markdown形式で記事を書いてください..." />
            </div>
          </div>

          {/* SEO設定 */}
          <div className="bg-white rounded-xl border border-gray-100 p-5 space-y-4">
            <h2 className="font-semibold text-gray-800">🔍 SEO設定</h2>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">SEOタイトル</label>
              <input value={form.seoTitle} onChange={e => setForm(f => ({...f, seoTitle: e.target.value}))}
                className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none"
                placeholder="検索結果に表示されるタイトル（60文字以内）" />
              <p className="text-xs text-gray-400 mt-1">{form.seoTitle.length}/60文字</p>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">メタディスクリプション</label>
              <textarea value={form.seoDescription} onChange={e => setForm(f => ({...f, seoDescription: e.target.value}))}
                rows={2} className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none resize-none"
                placeholder="検索結果に表示される説明（120文字以内）" />
              <p className="text-xs text-gray-400 mt-1">{form.seoDescription.length}/120文字</p>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">キーワード</label>
              <input value={form.seoKeywords} onChange={e => setForm(f => ({...f, seoKeywords: e.target.value}))}
                className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none"
                placeholder="キーワード1,キーワード2,キーワード3" />
            </div>
          </div>
        </div>

        {/* 右サイドバー */}
        <div className="space-y-4">
          <div className="bg-white rounded-xl border border-gray-100 p-4">
            <h3 className="font-semibold text-gray-800 mb-3 text-sm">公開設定</h3>
            <div className="space-y-2">
              {["draft","published","scheduled"].map((s: any) => (
                <label key={s} className="flex items-center gap-2 cursor-pointer">
                  <input type="radio" name="status" value={s} checked={form.status === s}
                    onChange={() => setForm(f => ({...f, status: s}))} className="text-purple-600" />
                  <span className="text-sm">{({ draft:"下書き", published:"公開", scheduled:"予約公開" } as Record<string,string>)[s]}</span>
                </label>
              ))}
            </div>
          </div>
          <div className="bg-blue-50 rounded-xl border border-blue-100 p-4">
            <h3 className="font-semibold text-blue-800 mb-2 text-sm">💡 AI記事生成のヒント</h3>
            <p className="text-xs text-blue-700">キーワードを設定してAI生成ページから自動で記事を作成すると、SEO最適化済みの記事が数秒で完成します。</p>
            <a href="/admin/generate" className="text-xs text-blue-600 hover:underline mt-2 block">AI生成ページへ →</a>
          </div>
        </div>
      </div>
    </div>
  );
}
