/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI v2056.8
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * Redistribution / derivative-work / reverse-engineering prohibited
 * (著作権法 / 不正競争防止法 / 当社利用規約 第 8 条).
 * License inquiries: nomura.y@soloptilink.com
 * ----------------------------------------------------------------*/
// ChatGPT で作ってダウンロードした画像（~/Downloads/<名前>.png）を、
// 軽量な WebP に変換して public/covers に置き、lib/cover-manifest.json を更新する。
// 同じ名前が複数あれば（"名前 (1).png" など）いちばん新しいものを採用する。
//
// 使い方: node scripts/import-covers.mjs [取り込み元フォルダ]
import sharp from "sharp";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const SRC = process.argv[2] || path.join(os.homedir(), "Downloads");
const ROOT = process.cwd();
const OUT = path.join(ROOT, "public", "covers");
const MANIFEST = path.join(ROOT, "lib", "cover-manifest.json");
fs.mkdirSync(OUT, { recursive: true });

const NAME = /^((?:c-[0-9a-f]{10})|(?:category-[a-z-]+)|(?:hero-home))(?: \(\d+\))?\.png$/;

const latest = new Map();
for (const f of fs.readdirSync(SRC)) {
  const m = f.match(NAME);
  if (!m) continue;
  const full = path.join(SRC, f);
  const mtime = fs.statSync(full).mtimeMs;
  const cur = latest.get(m[1]);
  if (!cur || cur.mtime < mtime) latest.set(m[1], { full, mtime });
}

let converted = 0;
for (const [name, { full, mtime }] of latest) {
  const dest = path.join(OUT, `${name}.webp`);
  if (fs.existsSync(dest) && fs.statSync(dest).mtimeMs >= mtime) continue;
  await sharp(full).resize(1600, 1067, { fit: "cover" }).webp({ quality: 78 }).toFile(dest);
  converted++;
}

const all = fs
  .readdirSync(OUT)
  .filter((f) => f.endsWith(".webp"))
  .map((f) => f.replace(/\.webp$/, ""))
  .sort();
fs.writeFileSync(MANIFEST, JSON.stringify(all) + "\n");
console.log(`変換 ${converted} 件 / 掲載可能な画像 合計 ${all.length} 件`);
