/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI v2056.8
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * Redistribution / derivative-work / reverse-engineering prohibited
 * (著作権法 / 不正競争防止法 / 当社利用規約 第 8 条).
 * License inquiries: nomura.y@soloptilink.com
 * ----------------------------------------------------------------*/
import Image from "next/image";
import Link from "next/link";
import { categoryMeta, coverFor, formatDateJa } from "@/lib/media";

export type CardArticle = {
  id: string;
  slug: string;
  title: string;
  excerpt?: string | null;
  publishedAt?: Date | string | null;
  createdAt?: Date | string | null;
  readingTime?: number | null;
  category?: { slug: string; name: string } | null;
};

type Variant = "lead" | "feature" | "standard" | "compact" | "row";

function Meta({ a, light = false }: { a: CardArticle; light?: boolean }) {
  const date = a.publishedAt || a.createdAt;
  return (
    <div className={`mt-3 flex items-center gap-3 text-[11.5px] ${light ? "text-white/80" : "text-mute"}`}>
      {date && (
        <time className="font-[family-name:var(--font-latin)] tracking-wide" dateTime={new Date(date).toISOString()}>
          {formatDateJa(date)}
        </time>
      )}
      {a.readingTime ? <span>{a.readingTime}分で読める</span> : null}
    </div>
  );
}

function Kicker({ a, light = false }: { a: CardArticle; light?: boolean }) {
  return <p className={`text-[12px] font-bold ${light ? "text-white" : "text-accent-deep"}`}>{categoryMeta(a.category?.slug)?.name ?? a.category?.name ?? "AI活用"}</p>;
}

export default function ArticleCard({ a, variant = "standard", priority = false, sizes }: { a: CardArticle; variant?: Variant; priority?: boolean; sizes?: string }) {
  const src = coverFor(a.slug, a.category?.slug);
  const href = `/articles/${a.slug}`;

  if (variant === "lead") {
    return (
      <Link href={href} className="group block">
        <div className="relative aspect-[16/10] overflow-hidden bg-paper-deep">
          <Image src={src} alt="" fill preload={priority} sizes={sizes ?? "(min-width: 1024px) 820px, 100vw"} className="img-zoom object-cover" />
        </div>
        <div className="mt-5">
          <Kicker a={a} />
          <h2 className="headline mt-2 text-[26px] text-ink md:text-[34px] md:leading-[1.4]">
            <span className="link-underline">{a.title}</span>
          </h2>
          {a.excerpt && <p className="mt-3 line-clamp-2 text-[15px] leading-[1.85] text-ink-soft md:line-clamp-3">{a.excerpt}</p>}
          <Meta a={a} />
        </div>
      </Link>
    );
  }

  if (variant === "feature") {
    return (
      <Link href={href} className="group relative block overflow-hidden bg-ink">
        <div className="relative aspect-[4/5] sm:aspect-[3/4]">
          <Image src={src} alt="" fill sizes={sizes ?? "(min-width: 1024px) 400px, 100vw"} className="img-zoom object-cover opacity-90" />
          <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/65 via-45% to-black/10" />
        </div>
        <div className="absolute inset-x-0 bottom-0 p-6">
          <Kicker a={a} light />
          <h3 className="headline mt-2 text-[20px] text-white">{a.title}</h3>
          <Meta a={a} light />
        </div>
      </Link>
    );
  }

  if (variant === "compact") {
    return (
      <Link href={href} className="group grid grid-cols-[1fr_96px] items-start gap-4 sm:grid-cols-[1fr_112px]">
        <div>
          <Kicker a={a} />
          <h3 className="mt-1.5 line-clamp-3 text-[15px] font-bold leading-[1.6] text-ink">
            <span className="link-underline">{a.title}</span>
          </h3>
          <Meta a={a} />
        </div>
        <div className="relative aspect-square overflow-hidden bg-paper-deep">
          <Image src={src} alt="" fill sizes="112px" className="img-zoom object-cover" />
        </div>
      </Link>
    );
  }

  if (variant === "row") {
    return (
      <Link href={href} className="group grid grid-cols-1 gap-5 sm:grid-cols-[280px_1fr] sm:gap-8">
        <div className="relative aspect-[16/10] overflow-hidden bg-paper-deep">
          <Image src={src} alt="" fill sizes="(min-width: 640px) 280px, 100vw" className="img-zoom object-cover" />
        </div>
        <div className="self-center">
          <Kicker a={a} />
          <h3 className="headline mt-2 text-[20px] text-ink">
            <span className="link-underline">{a.title}</span>
          </h3>
          {a.excerpt && <p className="mt-2 line-clamp-2 text-[14px] leading-[1.85] text-ink-soft">{a.excerpt}</p>}
          <Meta a={a} />
        </div>
      </Link>
    );
  }

  return (
    <Link href={href} className="group block">
      <div className="relative aspect-[3/2] overflow-hidden bg-paper-deep">
        <Image src={src} alt="" fill preload={priority} sizes={sizes ?? "(min-width: 1024px) 380px, (min-width: 640px) 50vw, 100vw"} className="img-zoom object-cover" />
      </div>
      <div className="mt-4">
        <Kicker a={a} />
        <h3 className="mt-1.5 line-clamp-3 text-[17px] font-bold leading-[1.6] text-ink">
          <span className="link-underline">{a.title}</span>
        </h3>
        <Meta a={a} />
      </div>
    </Link>
  );
}

export function SectionHeading({ en, ja, href, linkLabel = "もっと見る" }: { en: string; ja: string; href?: string; linkLabel?: string }) {
  return (
    <div className="section-rule mb-8 justify-between">
      <div className="flex items-baseline gap-4">
        <h2 className="text-[22px] font-black tracking-[0.04em] text-ink md:text-[26px]">{ja}</h2>
        <span className="kicker text-mute">{en}</span>
      </div>
      {href && (
        <Link href={href} className="group shrink-0 text-[13px] font-bold text-ink hover:text-accent">
          {linkLabel} <span aria-hidden className="inline-block transition-transform group-hover:translate-x-1">→</span>
        </Link>
      )}
    </div>
  );
}
