"use client";
/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI v2056.8
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * Redistribution / derivative-work / reverse-engineering prohibited
 * (著作権法 / 不正競争防止法 / 当社利用規約 第 8 条).
 * License inquiries: nomura.y@soloptilink.com
 * ----------------------------------------------------------------*/
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useRef, useState } from "react";

type Cat = { slug: string; name: string };

export function Wordmark({ invert = false }: { invert?: boolean }) {
  return (
    <span className="flex items-center gap-2.5">
      <span aria-hidden className="block h-[18px] w-[18px] bg-accent" />
      <span
        className={`text-[19px] font-black tracking-[0.04em] ${invert ? "text-white" : "text-ink"}`}
      >
        AI活用ラボ
      </span>
      <span
        className={`kicker hidden sm:inline ${invert ? "text-white/50" : "text-mute"}`}
      >
        AI Katsuyo Lab
      </span>
    </span>
  );
}

export default function SiteHeader({
  categories,
  today,
}: {
  categories: Cat[];
  today: string;
}) {
  const pathname = usePathname();
  const [open, setOpen] = useState(false);

  const toggleRef = useRef<HTMLButtonElement>(null);
  const panelRef = useRef<HTMLDivElement>(null);

  // ページを移動したらメニューを閉じる（描画中に前回のパスと比べて調整する）
  const [shownPath, setShownPath] = useState(pathname);
  if (shownPath !== pathname) {
    setShownPath(pathname);
    setOpen(false);
  }
  useEffect(() => {
    if (!open) return;
    const main = document.getElementById("main");
    const footer = document.querySelector("footer");
    document.documentElement.style.overflow = "hidden";
    main?.setAttribute("inert", "");
    footer?.setAttribute("inert", "");
    panelRef.current?.querySelector<HTMLElement>("a, input, button")?.focus();
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        setOpen(false);
        toggleRef.current?.focus();
      }
    };
    document.addEventListener("keydown", onKey);
    return () => {
      document.documentElement.style.overflow = "";
      main?.removeAttribute("inert");
      footer?.removeAttribute("inert");
      document.removeEventListener("keydown", onKey);
    };
  }, [open]);

  return (
    <>
      <header className="sticky top-0 z-40 border-b border-line bg-paper/95 backdrop-blur-md">
        <div className="hidden border-b border-line md:block">
          <div className="mx-auto flex h-8 max-w-[1240px] items-center justify-between px-6 text-[11px] text-mute">
            <span className="font-[family-name:var(--font-latin)] tracking-wider">
              {today}
            </span>
            <span>仕事で使えるAIを、いちばん実践的に。</span>
          </div>
        </div>
        <div className="mx-auto flex h-16 max-w-[1240px] items-center justify-between gap-6 px-5 md:px-6">
          <Link href="/" aria-label="AI活用ラボ トップへ">
            <Wordmark />
          </Link>
          <nav aria-label="カテゴリ" className="hidden items-center lg:flex">
            {categories.map((c) => {
              const active = pathname === `/category/${c.slug}`;
              return (
                <Link
                  key={c.slug}
                  href={`/category/${c.slug}`}
                  aria-current={active ? "page" : undefined}
                  className={`relative px-3 py-2 text-[13px] font-bold transition-colors ${active ? "text-accent-deep" : "text-ink-soft hover:text-ink"}`}
                >
                  {c.name}
                  {active && (
                    <span className="absolute inset-x-3 -bottom-[13px] h-[2px] bg-accent" />
                  )}
                </Link>
              );
            })}
          </nav>
          <div className="flex items-center gap-1">
            <Link
              href="/search"
              aria-label="記事を検索"
              className="grid h-10 w-10 place-items-center text-ink hover:text-accent"
            >
              <svg
                width="19"
                height="19"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                aria-hidden
              >
                <circle cx="11" cy="11" r="7" />
                <path d="m20 20-3.5-3.5" />
              </svg>
            </Link>
            <button
              ref={toggleRef}
              type="button"
              onClick={() => setOpen((v) => !v)}
              aria-expanded={open}
              aria-controls="mobile-nav"
              aria-label={open ? "メニューを閉じる" : "メニューを開く"}
              className="grid h-10 w-10 place-items-center text-ink lg:hidden"
            >
              <svg
                width="20"
                height="20"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                aria-hidden
              >
                {open ? (
                  <path d="M6 6l12 12M18 6 6 18" />
                ) : (
                  <path d="M3 7h18M3 12h18M3 17h18" />
                )}
              </svg>
            </button>
          </div>
        </div>
      </header>
      {/* ぼかし付きヘッダーの外に置く（中に置くと fixed の基準がヘッダーになり高さが潰れる） */}
      {open && (
        <div
          id="mobile-nav"
          ref={panelRef}
          className="fixed inset-x-0 top-16 bottom-0 z-40 overflow-y-auto overscroll-contain bg-paper md:top-[97px] lg:hidden"
        >
          <nav aria-label="カテゴリ（モバイル）" className="px-5 py-6">
            <p className="kicker mb-3 text-mute">Categories</p>
            <ul className="divide-y divide-line border-y border-line">
              {categories.map((c) => (
                <li key={c.slug}>
                  <Link
                    href={`/category/${c.slug}`}
                    className="flex items-center justify-between py-4 text-[17px] font-bold text-ink"
                  >
                    {c.name}
                    <span aria-hidden className="text-accent">
                      →
                    </span>
                  </Link>
                </li>
              ))}
              <li>
                <Link
                  href="/articles"
                  className="flex items-center justify-between py-4 text-[17px] font-bold text-ink"
                >
                  すべての記事
                  <span aria-hidden className="text-accent">
                    →
                  </span>
                </Link>
              </li>
            </ul>
            <form
              action="/search"
              method="get"
              role="search"
              className="mt-8 flex border-b-2 border-ink focus-within:border-accent-deep"
            >
              <label htmlFor="m-search" className="sr-only">
                記事を検索
              </label>
              <input
                id="m-search"
                name="q"
                placeholder="キーワードで探す"
                className="min-w-0 flex-1 bg-transparent py-3 text-base outline-none placeholder:text-mute"
              />
              <button type="submit" className="px-2 text-sm font-bold">
                検索
              </button>
            </form>
          </nav>
        </div>
      )}
    </>
  );
}
