/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * ----------------------------------------------------------------*/
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { z } from "zod";
import { estimateReadingTime } from "@/lib/utils";

const UpdateSchema = z.object({
  title: z.string().min(1).optional(),
  excerpt: z.string().optional(),
  content: z.string().optional(),
  categoryId: z.string().nullable().optional(),
  status: z.enum(["draft", "published", "scheduled"]).optional(),
  seoTitle: z.string().optional(),
  seoDescription: z.string().optional(),
  seoKeywords: z.string().optional(),
});

export async function GET(_: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const article = await prisma.article.findUnique({
    where: { id },
    include: { category: true, tags: { include: { tag: true } }, _count: { select: { views: true } } },
  });
  if (!article) return NextResponse.json({ error: "見つかりません" }, { status: 404 });
  return NextResponse.json(article);
}

export async function PUT(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  try {
    const body = await req.json();
    const data = UpdateSchema.parse(body);
    const updates: any = { ...data };
    if (data.content) {
      updates.wordCount = data.content.split(/\s+/).length;
      updates.readingTime = estimateReadingTime(data.content);
    }
    if (data.status === "published") updates.publishedAt = new Date();
    const article = await prisma.article.update({ where: { id }, data: updates });
    return NextResponse.json(article);
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 400 });
  }
}

export async function DELETE(_: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  await prisma.article.delete({ where: { id } });
  return NextResponse.json({ success: true });
}
