/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI v2056.8
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * Redistribution / derivative-work / reverse-engineering prohibited
 * (著作権法 / 不正競争防止法 / 当社利用規約 第 8 条).
 * License inquiries: nomura.y@soloptilink.com
 * ----------------------------------------------------------------*/
export default function Loading() {
  return (
    <main className="animate-pulse" aria-busy="true" aria-label="読み込み中">
      <div className="mx-auto max-w-[860px] px-5 pt-16 md:px-6">
        <div className="h-3 w-24 bg-paper-deep" />
        <div className="mt-6 h-9 w-full bg-paper-deep" />
        <div className="mt-3 h-9 w-3/4 bg-paper-deep" />
        <div className="mt-8 h-4 w-full bg-paper-deep" />
        <div className="mt-2 h-4 w-5/6 bg-paper-deep" />
      </div>
      <div className="mx-auto mt-10 aspect-[16/10] max-w-[1100px] bg-paper-deep" />
    </main>
  );
}
