/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
export default function ArticleLoading() {
  return (
    <main className="max-w-6xl mx-auto px-4 py-8">
      {/* パンくず */}
      <div className="flex gap-2 mb-6">
        {[3, 4, 6, 12].map((w, i) => (
          <div key={i} className="flex items-center gap-2">
            <div className={`h-3 w-${w * 4} bg-gray-200 rounded animate-pulse`} />
            {i < 3 && <span className="text-gray-300">›</span>}
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-[1fr_300px] gap-10">
        <article className="space-y-4">
          {/* カテゴリ */}
          <div className="h-6 w-24 bg-purple-100 rounded-full animate-pulse" />
          {/* タイトル */}
          <div className="space-y-2">
            <div className="h-8 w-full bg-gray-200 rounded animate-pulse" />
            <div className="h-8 w-4/5 bg-gray-200 rounded animate-pulse" />
          </div>
          {/* メタ */}
          <div className="flex gap-4 py-4 border-y border-gray-100">
            <div className="h-4 w-24 bg-gray-100 rounded animate-pulse" />
            <div className="h-4 w-24 bg-gray-100 rounded animate-pulse" />
          </div>
          {/* リード文 */}
          <div className="bg-purple-50 rounded-xl p-5 space-y-2">
            <div className="h-4 w-full bg-purple-100 rounded animate-pulse" />
            <div className="h-4 w-5/6 bg-purple-100 rounded animate-pulse" />
            <div className="h-4 w-4/5 bg-purple-100 rounded animate-pulse" />
          </div>
          {/* 目次 */}
          <div className="bg-gray-50 rounded-xl p-5 space-y-2">
            <div className="h-5 w-16 bg-gray-200 rounded animate-pulse mb-3" />
            {Array.from({ length: 5 }).map((_, i) => (
              <div key={i} className={`h-4 bg-gray-200 rounded animate-pulse`} style={{ width: `${70 + i * 5}%` }} />
            ))}
          </div>
          {/* 本文 */}
          <div className="space-y-3 mt-4">
            {Array.from({ length: 15 }).map((_, i) => (
              <div key={i} className={`h-4 bg-gray-200 rounded animate-pulse`} style={{ width: `${60 + Math.random() * 40}%` }} />
            ))}
          </div>
        </article>

        {/* サイドバー */}
        <aside className="space-y-5">
          <div className="bg-gradient-to-br from-purple-600 to-indigo-600 rounded-xl p-5 h-32 animate-pulse" />
          <div className="bg-white border border-gray-100 rounded-xl p-5 space-y-3">
            <div className="h-5 w-20 bg-gray-200 rounded animate-pulse" />
            {Array.from({ length: 5 }).map((_, i) => (
              <div key={i} className="h-8 w-full bg-gray-100 rounded animate-pulse" />
            ))}
          </div>
        </aside>
      </div>
    </main>
  );
}
