/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
import { ImageResponse } from "next/og";
import { prisma } from "@/lib/prisma";

export const runtime = "nodejs";
export const alt = "AI活用ラボ";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default async function OGImage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const article = await prisma.article.findUnique({
    where: { slug },
    include: { category: true },
  });

  const title = article?.title || "AI活用ラボ";
  const category = article?.category?.name || "AI活用";

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          background: "linear-gradient(135deg, #4c1d95 0%, #3730a3 100%)",
          padding: "60px",
          fontFamily: "sans-serif",
        }}
      >
        {/* ヘッダー */}
        <div style={{ display: "flex", alignItems: "center", gap: "16px" }}>
          <div style={{ fontSize: "40px" }}>🤖</div>
          <div style={{ color: "rgba(255,255,255,0.8)", fontSize: "24px", fontWeight: "bold" }}>
            AI活用ラボ
          </div>
        </div>

        {/* タイトル */}
        <div style={{ flex: 1, display: "flex", alignItems: "center", paddingTop: "40px" }}>
          <div
            style={{
              fontSize: title.length > 40 ? "40px" : "52px",
              fontWeight: "900",
              color: "white",
              lineHeight: 1.3,
              letterSpacing: "-0.02em",
            }}
          >
            {title}
          </div>
        </div>

        {/* フッター */}
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <div
            style={{
              background: "rgba(255,255,255,0.15)",
              color: "white",
              fontSize: "20px",
              padding: "8px 20px",
              borderRadius: "999px",
              border: "1px solid rgba(255,255,255,0.3)",
            }}
          >
            {category}
          </div>
          <div style={{ color: "rgba(255,255,255,0.6)", fontSize: "18px" }}>
            media.seasonsezon.co.jp
          </div>
        </div>
      </div>
    ),
    { ...size }
  );
}
