/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI v2056.8
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * Redistribution / derivative-work / reverse-engineering prohibited
 * (著作権法 / 不正競争防止法 / 当社利用規約 第 8 条).
 * License inquiries: nomura.y@soloptilink.com
 * ----------------------------------------------------------------*/
// 記事専用の写真がまだ無い記事（新着の自動生成記事など）向けの、タイトル入りシェア画像
import { ImageResponse } from "next/og";
import { prisma } from "@/lib/prisma";
import { categoryMeta } from "@/lib/media";

// 日本語を含むURLは、経路によってエンコードされたまま届くことがあるため必ず復号してから照合する
function safeDecode(s: string) {
  try {
    return decodeURIComponent(s);
  } catch {
    return s;
  }
}

export const runtime = "nodejs";
export const alt = "AI活用ラボ";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

/** 画像内で使う文字だけを含む日本語フォントを取得する（取れなければ既定フォントで描く） */
async function loadFont(text: string): Promise<ArrayBuffer | null> {
  try {
    const css = await fetch(`https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@700&text=${encodeURIComponent(text)}`, {
      headers: { "User-Agent": "Mozilla/5.0" },
    }).then((r) => r.text());
    const url = css.match(/src: url\((.+?)\) format/)?.[1];
    if (!url) return null;
    return await fetch(url).then((r) => r.arrayBuffer());
  } catch {
    return null;
  }
}

export default async function OGImage({ params }: { params: Promise<{ slug: string }> }) {
  const slug = safeDecode((await params).slug);
  const article = await prisma.article
    .findUnique({ where: { slug }, include: { category: true } })
    .catch(() => null);

  const title = article?.title || "AI活用ラボ";
  const category = categoryMeta(article?.category?.slug)?.name ?? article?.category?.name ?? "AI活用";
  const font = await loadFont(`${title}${category}AI活用ラボ`);

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          background: "#f7f5f0",
          padding: "64px 72px",
          borderTop: "14px solid #141414",
          fontFamily: font ? "NotoSansJP" : "sans-serif",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: "16px" }}>
          <div style={{ width: "28px", height: "28px", background: "#c4351a" }} />
          <div style={{ color: "#141414", fontSize: "30px", fontWeight: 700 }}>AI活用ラボ</div>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: "20px" }}>
          <div style={{ color: "#a82c12", fontSize: "26px", fontWeight: 700 }}>{category}</div>
          <div style={{ color: "#141414", fontSize: title.length > 36 ? "50px" : "60px", fontWeight: 700, lineHeight: 1.4 }}>{title}</div>
        </div>
        <div style={{ display: "flex", justifyContent: "space-between", color: "#64625c", fontSize: "22px" }}>
          <div>media.seasonsezon.co.jp</div>
          <div>運営：株式会社セゾン</div>
        </div>
      </div>
    ),
    { ...size, ...(font ? { fonts: [{ name: "NotoSansJP", data: font, weight: 700 as const, style: "normal" as const }] } : {}) },
  );
}
