/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI v2056.8
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * Redistribution / derivative-work / reverse-engineering prohibited
 * (著作権法 / 不正競争防止法 / 当社利用規約 第 8 条).
 * License inquiries: nomura.y@soloptilink.com
 * ----------------------------------------------------------------*/
import { notFound } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
import { prisma } from "@/lib/prisma";
import ShareButtons from "@/components/ShareButtons";
import TableOfContents from "@/components/TableOfContents";
import ScrollDepthTracker from "@/components/ScrollDepthTracker";
import ArticleCard, { SectionHeading, type CardArticle } from "@/components/media/ArticleCard";
import { extractFAQ, extractHeadings, renderArticle } from "@/lib/markdown";
import { OPERATOR, SITE_NAME, SITE_URL, categoryMeta, coverFor, formatDateJa, hasOwnCover } from "@/lib/media";

// 日本語を含むURLは、経路によってエンコードされたまま届くことがあるため必ず復号してから照合する
function safeDecode(s: string) {
  try {
    return decodeURIComponent(s);
  } catch {
    return s;
  }
}

export const revalidate = 3600;
export const dynamicParams = true;

export async function generateStaticParams() {
  const articles = await prisma.article.findMany({
    where: { status: "published" },
    select: { slug: true },
    orderBy: { publishedAt: "desc" },
    take: 200,
  });
  return articles.map((a) => ({ slug: a.slug }));
}

const cardSelect = {
  id: true,
  slug: true,
  title: true,
  excerpt: true,
  publishedAt: true,
  createdAt: true,
  readingTime: true,
  category: { select: { slug: true, name: true } },
} as const;

async function getArticle(slug: string) {
  return prisma.article.findUnique({
    where: { slug },
    include: { category: true, tags: { include: { tag: true } }, affiliateLinks: { include: { product: true } } },
  });
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const slug = safeDecode((await params).slug);
  const article = await getArticle(slug);
  if (!article) return { title: "記事が見つかりません" };
  const title = article.seoTitle || article.title;
  const description = article.seoDescription || article.excerpt;
  // 同じタイトルの記事が複数ある場合は、いちばん内容の多い1本を正規URLにして評価の分散を防ぐ
  const twins = await prisma.article.findMany({
    where: { status: "published", title: article.title },
    select: { slug: true, wordCount: true, publishedAt: true },
  });
  const primary = twins.sort((a, b) => b.wordCount - a.wordCount || (a.publishedAt?.getTime() ?? 0) - (b.publishedAt?.getTime() ?? 0))[0];
  const url = `${SITE_URL}/articles/${(primary ?? article).slug}`;
  // 記事専用の写真がある記事だけ写真を使い、無い記事は記事タイトル入りの自動生成画像（opengraph-image）に任せる
  const ogImages = hasOwnCover(article.slug) ? [{ url: coverFor(article.slug), width: 1600, height: 1067 }] : undefined;
  return {
    title,
    description,
    keywords: article.seoKeywords || undefined,
    alternates: { canonical: url },
    openGraph: {
      title,
      description,
      type: "article",
      url,
      publishedTime: article.publishedAt?.toISOString(),
      modifiedTime: article.updatedAt?.toISOString(),
      siteName: SITE_NAME,
      locale: "ja_JP",
      ...(ogImages ? { images: ogImages } : {}),
    },
    twitter: { card: "summary_large_image", title, description, ...(ogImages ? { images: ogImages.map((i) => i.url) } : {}) },
  };
}

export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const slug = safeDecode((await params).slug);
  const article = await getArticle(slug);
  if (!article || article.status !== "published") notFound();

  prisma.articleView.create({ data: { articleId: article.id, referer: "direct" } }).catch(() => {});

  const [related, popular, linkTargets] = await Promise.all([
    prisma.article.findMany({
      where: { status: "published", NOT: { id: article.id }, ...(article.categoryId ? { categoryId: article.categoryId } : {}) },
      select: cardSelect,
      orderBy: { publishedAt: "desc" },
      take: 3,
    }),
    prisma.article.findMany({
      where: { status: "published", NOT: { id: article.id } },
      select: cardSelect,
      orderBy: { views: { _count: "desc" } },
      take: 5,
    }),
    prisma.article.findMany({
      where: { status: "published", NOT: { id: article.id } },
      select: { slug: true, title: true },
      orderBy: { publishedAt: "desc" },
      take: 100,
    }),
  ]);

  const html = renderArticle(article.content, linkTargets);
  const headings = extractHeadings(article.content);
  const faqs = extractFAQ(article.content);
  const articleUrl = `${SITE_URL}/articles/${article.slug}`;
  const title = article.seoTitle || article.title;
  const cover = coverFor(article.slug, article.category?.slug);
  const published = article.publishedAt || article.createdAt;
  const updated = article.updatedAt && published && article.updatedAt.getTime() - new Date(published).getTime() > 86400000 ? article.updatedAt : null;

  const articleJsonLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: article.title,
    description: article.excerpt,
    url: articleUrl,
    image: [`${SITE_URL}${cover}`],
    datePublished: published?.toISOString(),
    dateModified: (article.updatedAt || published)?.toISOString(),
    author: { "@type": "Organization", name: "AI活用ラボ編集部", url: SITE_URL },
    publisher: { "@type": "Organization", name: OPERATOR.name, url: OPERATOR.url, logo: { "@type": "ImageObject", url: `${SITE_URL}/logo.png`, width: 512, height: 512 } },
    timeRequired: article.readingTime ? `PT${article.readingTime}M` : undefined,
    mainEntityOfPage: { "@type": "WebPage", "@id": articleUrl },
    inLanguage: "ja",
    wordCount: article.wordCount,
    keywords: article.seoKeywords || undefined,
    articleSection: article.category?.name || "AI活用",
  };
  const breadcrumbJsonLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "ホーム", item: SITE_URL },
      ...(article.category ? [{ "@type": "ListItem", position: 2, name: article.category.name, item: `${SITE_URL}/category/${article.category.slug}` }] : []),
      { "@type": "ListItem", position: article.category ? 3 : 2, name: article.title, item: articleUrl },
    ],
  };
  const faqJsonLd = faqs.length
    ? {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        mainEntity: faqs.map((f) => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })),
      }
    : null;

  return (
    <>
      <ScrollDepthTracker articleTitle={article.title} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }} />
      {faqJsonLd && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />}

      <main>
        <article>
          {/* 見出し */}
          <header className="mx-auto max-w-[860px] px-5 pt-10 md:px-6 md:pt-16">
            <nav aria-label="パンくずリスト" className="flex flex-wrap items-center gap-2 text-[12px] text-mute">
              <Link href="/" className="hover:text-ink">ホーム</Link>
              <span aria-hidden>/</span>
              {article.category ? (
                <Link href={`/category/${article.category.slug}`} className="font-bold text-accent-deep hover:text-accent">{categoryMeta(article.category.slug)?.name ?? article.category.name}</Link>
              ) : (
                <Link href="/articles" className="hover:text-ink">記事一覧</Link>
              )}
            </nav>
            <h1 className="headline mt-5 text-[28px] leading-[1.45] text-ink md:text-[40px] md:leading-[1.4]">{article.title}</h1>
            {article.excerpt && <p className="mt-6 text-[16px] leading-[1.95] text-ink-soft md:text-[17px]">{article.excerpt}</p>}
            <div className="mt-8 flex flex-wrap items-center justify-between gap-4 border-y border-line py-4">
              <div className="flex items-center gap-3">
                <span aria-hidden className="grid h-10 w-10 place-items-center bg-ink">
                  <span className="block h-3 w-3 bg-accent" />
                </span>
                <div className="text-[12px] leading-[1.6]">
                  <p className="font-bold text-ink">AI活用ラボ編集部</p>
                  <p className="text-mute">
                    <time dateTime={published?.toISOString()}>{formatDateJa(published)}</time>
                    {updated && <> ／ 更新 <time dateTime={updated.toISOString()}>{formatDateJa(updated)}</time></>}
                    {article.readingTime ? <> ／ {article.readingTime}分で読める</> : null}
                  </p>
                </div>
              </div>
              <ShareButtons url={articleUrl} title={title} />
            </div>
          </header>

          <figure className="mx-auto mt-10 max-w-[1100px] md:px-6">
            <div className="relative aspect-[16/10] overflow-hidden bg-paper-deep">
              <Image src={cover} alt="" fill preload sizes="(min-width: 1100px) 1100px, 100vw" className="object-cover" />
            </div>
          </figure>

          {/* 本文 */}
          <div className="mx-auto mt-14 grid max-w-[1100px] gap-12 px-5 md:px-6 xl:grid-cols-[minmax(0,720px)_1fr] xl:gap-16">
            <div className="min-w-0">
              {headings.length >= 3 && (
                <div className="xl:hidden">
                  <TableOfContents headings={headings} />
                </div>
              )}
              <div className="article-body" dangerouslySetInnerHTML={{ __html: html }} />

              {article.affiliateLinks.length > 0 && (
                <aside className="mt-14 border border-line bg-white p-6">
                  <p className="kicker text-accent-deep">Tools in this article</p>
                  <h2 className="mt-2 text-[17px] font-bold">この記事で紹介したツール・サービス</h2>
                  <ul className="mt-5 divide-y divide-line">
                    {article.affiliateLinks.map((al) => (
                      <li key={al.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between">
                        <div>
                          <p className="text-[15px] font-bold">{al.product.name}</p>
                          {al.product.description && <p className="mt-0.5 text-[13px] text-mute">{al.product.description}</p>}
                        </div>
                        <a href={al.product.url} target="_blank" rel="noopener noreferrer sponsored" className="shrink-0 bg-ink px-5 py-2.5 text-center text-[13px] font-bold text-white hover:bg-accent">
                          公式サイトを見る
                        </a>
                      </li>
                    ))}
                  </ul>
                  <p className="mt-3 text-[11px] text-mute">※ 本欄のリンクには広告（アフィリエイト）を含みます。</p>
                </aside>
              )}

              {article.tags.length > 0 && (
                <ul className="mt-12 flex flex-wrap gap-2">
                  {article.tags.map((at) => (
                    <li key={at.tagId} className="border border-line px-3 py-1.5 text-[12px] text-ink-soft">#{at.tag.name}</li>
                  ))}
                </ul>
              )}

              <div className="mt-12 flex flex-col items-start justify-between gap-4 border-y-2 border-ink py-6 sm:flex-row sm:items-center">
                <p className="text-[14px] font-bold">この記事をシェアする</p>
                <ShareButtons url={articleUrl} title={title} />
              </div>

              {/* 編集部・運営 */}
              <section className="mt-12 grid gap-5 bg-white p-6 sm:grid-cols-[56px_1fr] md:p-8">
                <span aria-hidden className="grid h-14 w-14 place-items-center bg-ink">
                  <span className="block h-4 w-4 bg-accent" />
                </span>
                <div>
                  <p className="kicker text-mute">About</p>
                  <p className="mt-1 text-[16px] font-bold">AI活用ラボ編集部</p>
                  <p className="mt-2 text-[13.5px] leading-[1.9] text-ink-soft">
                    生成AIの使い方・比較・業務への導入事例を、実務の目線で整理してお届けしています。運営は、SNS運用代行とAIシステムの導入支援を行う{OPERATOR.name}です。
                    {article.aiGenerated && " 本記事はAIによる下書きをもとに作成しています。"}
                  </p>
                  <a href={OPERATOR.url} target="_blank" rel="noopener" className="mt-4 inline-flex items-center gap-2 text-[13px] font-bold text-accent hover:text-accent-deep">
                    AI導入の相談をする <span aria-hidden>→</span>
                  </a>
                </div>
              </section>
            </div>

            {/* サイド */}
            <aside className="hidden xl:block">
              <div className="sticky top-32 space-y-12">
                {headings.length >= 3 && <TableOfContents headings={headings} variant="side" />}
                {popular.length > 0 && (
                  <div>
                    <p className="section-rule kicker text-ink">Ranking</p>
                    <ol className="mt-4 space-y-5">
                      {(popular as CardArticle[]).map((p, i) => (
                        <li key={p.id}>
                          <Link href={`/articles/${p.slug}`} className="group grid grid-cols-[28px_1fr] gap-2">
                            <span className="font-[family-name:var(--font-latin)] text-[20px] leading-none font-normal text-accent-deep">{i + 1}</span>
                            <span className="line-clamp-3 text-[13px] font-bold leading-[1.6] text-ink">
                              <span className="link-underline">{p.title}</span>
                            </span>
                          </Link>
                        </li>
                      ))}
                    </ol>
                  </div>
                )}
              </div>
            </aside>
          </div>
        </article>

        {related.length > 0 && (
          <section className="mx-auto mt-24 max-w-[1240px] px-5 md:px-6">
            <SectionHeading ja="あわせて読みたい" en="Related" href={article.category ? `/category/${article.category.slug}` : "/articles"} />
            <div className="grid gap-x-8 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">
              {(related as CardArticle[]).map((r) => (
                <ArticleCard key={r.id} a={r} />
              ))}
            </div>
          </section>
        )}
      </main>
    </>
  );
}
