/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
import { notFound } from "next/navigation";
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { formatDate } from "@/lib/utils";
import type { Metadata } from "next";

export const revalidate = 300;

async function getArticle(slug: string) {
  return prisma.article.findUnique({
    where: { slug },
    include: { category: true, tags: { include: { tag: true } }, affiliateLinks: { include: { product: true } } },
  });
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const article = await getArticle(slug);
  if (!article) return { title: "記事が見つかりません" };
  return {
    title: article.seoTitle || article.title,
    description: article.seoDescription || article.excerpt,
    keywords: article.seoKeywords || undefined,
    openGraph: {
      title: article.seoTitle || article.title,
      description: article.seoDescription || article.excerpt,
      type: "article",
      publishedTime: article.publishedAt?.toISOString(),
    },
  };
}

function renderMarkdown(content: string): string {
  return content
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\[(.+?)\]\((.+?)\)/g, '<a href="$2" target="_blank" rel="noopener noreferrer" class="text-purple-600 hover:underline">$1</a>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>)/gs, '<ul class="list-disc pl-6 mb-4 space-y-1">$1</ul>')
    .replace(/^\d+\. (.+)$/gm, '<li>$1</li>')
    .replace(/\n\n/g, '</p><p class="mb-4 leading-relaxed text-gray-700">')
    .replace(/^(?!<[hul]|<\/[hul])/gm, '')
    .replace(/^(.+)$/gm, (m) => m.startsWith('<') ? m : `<p class="mb-4 leading-relaxed text-gray-700">${m}</p>`);
}

export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const article = await getArticle(slug);
  if (!article || article.status !== "published") notFound();

  // Record view (non-blocking)
  prisma.articleView.create({ data: { articleId: article.id, referer: "direct" } }).catch(() => {});

  // Related articles
  const related = await prisma.article.findMany({
    where: { status: "published", categoryId: article.categoryId, NOT: { id: article.id } },
    include: { category: true },
    take: 3,
    orderBy: { views: { _count: "desc" } },
  });

  const htmlContent = renderMarkdown(article.content);

  return (
    <main className="max-w-5xl mx-auto px-4 py-10">
      <div className="grid grid-cols-3 gap-8">
        {/* Article */}
        <article className="col-span-2">
          {article.category && (
            <Link href={`/category/${article.category.slug}`}
              className="inline-block text-sm text-purple-600 bg-purple-50 px-3 py-1 rounded-full mb-4 hover:bg-purple-100">
              {article.category.name}
            </Link>
          )}
          <h1 className="text-2xl font-bold text-gray-900 mb-4 leading-tight">{article.title}</h1>
          <div className="flex items-center gap-4 text-sm text-gray-400 mb-6 pb-6 border-b border-gray-100">
            <span>📅 {formatDate(article.publishedAt || article.createdAt)}</span>
            <span>📖 約{article.readingTime}分</span>
            {article.aiGenerated && <span className="bg-purple-100 text-purple-600 text-xs px-2 py-0.5 rounded-full">AI生成記事</span>}
          </div>

          {/* Excerpt */}
          <div className="bg-purple-50 border border-purple-100 rounded-xl p-4 mb-6">
            <p className="text-sm text-gray-700 leading-relaxed">{article.excerpt}</p>
          </div>

          {/* Content */}
          <div className="prose max-w-none" dangerouslySetInnerHTML={{ __html: htmlContent }} />

          {/* Affiliate links */}
          {article.affiliateLinks.length > 0 && (
            <div className="mt-8 bg-amber-50 rounded-xl border border-amber-200 p-5">
              <h3 className="font-semibold text-amber-800 mb-3">🔗 おすすめツール・サービス</h3>
              <div className="space-y-3">
                {article.affiliateLinks.map((al: any) => (
                  <div key={al.id} className="flex items-center justify-between bg-white rounded-lg p-3 border border-amber-100">
                    <div>
                      <p className="font-medium text-gray-800 text-sm">{al.product.name}</p>
                      {al.product.description && <p className="text-xs text-gray-500">{al.product.description}</p>}
                    </div>
                    <a href={al.product.url} target="_blank" rel="noopener noreferrer sponsored"
                      className="bg-amber-500 hover:bg-amber-600 text-white text-xs px-4 py-2 rounded-lg font-medium whitespace-nowrap">
                      詳しくはこちら →
                    </a>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Tags */}
          {article.tags.length > 0 && (
            <div className="flex flex-wrap gap-2 mt-6">
              {article.tags.map((at: any) => (
                <span key={at.tagId} className="text-xs bg-gray-100 text-gray-600 px-3 py-1 rounded-full">#{at.tag.name}</span>
              ))}
            </div>
          )}
        </article>

        {/* Sidebar */}
        <aside className="space-y-5">
          <div className="bg-gradient-to-br from-purple-600 to-indigo-600 rounded-xl p-5 text-white">
            <h3 className="font-semibold mb-2">📩 お問い合わせ</h3>
            <p className="text-sm text-purple-200 mb-3">AI活用の相談・メディア掲載のご依頼はこちらから</p>
            <a href="mailto:contact@ai-media.jp" className="bg-white text-purple-600 text-sm font-medium px-4 py-2 rounded-lg hover:bg-purple-50 block text-center">
              メールで相談する
            </a>
          </div>

          {related.length > 0 && (
            <div className="bg-white rounded-xl border border-gray-100 p-5">
              <h3 className="font-semibold text-gray-800 mb-3 text-sm">関連記事</h3>
              <div className="space-y-3">
                {related.map((r: any) => (
                  <Link key={r.id} href={`/articles/${r.slug}`} className="block hover:bg-gray-50 rounded-lg p-2 -mx-2 transition-colors group">
                    <p className="text-sm text-gray-800 group-hover:text-purple-600 line-clamp-2 font-medium">{r.title}</p>
                    <p className="text-xs text-gray-400 mt-1">{r.category?.name}</p>
                  </Link>
                ))}
              </div>
            </div>
          )}
        </aside>
      </div>
    </main>
  );
}
