/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";

export default function NewKeywordPage() {
  const router = useRouter();
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ keyword: "", searchVolume: 0, difficulty: 50, priority: "medium", category: "" });
  const [bulkText, setBulkText] = useState("");
  const [bulkMode, setBulkMode] = useState(false);

  async function handleSave() {
    setSaving(true);
    if (bulkMode) {
      const lines = bulkText.split("\n").filter(l => l.trim());
      for (const line of lines) {
        await fetch("/api/keywords", {
          method: "POST", headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ keyword: line.trim(), priority: "medium" }),
        }).catch(() => {});
      }
    } else {
      await fetch("/api/keywords", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });
    }
    setSaving(false);
    router.push("/admin/keywords");
  }

  return (
    <div className="max-w-2xl space-y-5">
      <div className="flex items-center gap-3">
        <Link href="/admin/keywords" className="text-gray-400 hover:text-gray-600 text-sm">← キーワード一覧</Link>
        <h1 className="text-2xl font-bold text-gray-900">キーワード追加</h1>
      </div>

      <div className="bg-white rounded-xl border border-gray-100 p-5">
        <div className="flex gap-3 mb-5">
          <button onClick={() => setBulkMode(false)} className={`text-sm px-4 py-1.5 rounded-lg font-medium ${!bulkMode ? "bg-purple-600 text-white" : "bg-gray-100 text-gray-600"}`}>1件追加</button>
          <button onClick={() => setBulkMode(true)} className={`text-sm px-4 py-1.5 rounded-lg font-medium ${bulkMode ? "bg-purple-600 text-white" : "bg-gray-100 text-gray-600"}`}>一括追加</button>
        </div>

        {!bulkMode ? (
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">キーワード <span className="text-red-500">*</span></label>
              <input value={form.keyword} onChange={e => setForm(f => ({...f, keyword: e.target.value}))}
                className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none"
                placeholder="例: ChatGPT 使い方 初心者" />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">月間検索数</label>
                <input type="number" value={form.searchVolume} onChange={e => setForm(f => ({...f, searchVolume: Number(e.target.value)}))}
                  className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none" />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">難易度 (0-100)</label>
                <input type="number" min="0" max="100" value={form.difficulty} onChange={e => setForm(f => ({...f, difficulty: Number(e.target.value)}))}
                  className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none" />
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">優先度</label>
                <select value={form.priority} onChange={e => setForm(f => ({...f, priority: e.target.value}))}
                  className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none">
                  <option value="high">高優先</option>
                  <option value="medium">中優先</option>
                  <option value="low">低優先</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">カテゴリ</label>
                <input value={form.category} onChange={e => setForm(f => ({...f, category: e.target.value}))}
                  className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none"
                  placeholder="ChatGPT活用術" />
              </div>
            </div>
          </div>
        ) : (
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">キーワードリスト（1行1キーワード）</label>
            <textarea value={bulkText} onChange={e => setBulkText(e.target.value)} rows={12}
              className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none resize-none font-mono"
              placeholder={"ChatGPT 使い方\nAI 副業 稼ぎ方\nプロンプト テンプレート"} />
            <p className="text-xs text-gray-400 mt-1">{bulkText.split("\n").filter(l => l.trim()).length}件のキーワード</p>
          </div>
        )}

        <div className="flex gap-3 mt-5">
          <Link href="/admin/keywords" className="flex-1 text-center border border-gray-300 text-gray-600 py-2.5 rounded-lg text-sm font-medium hover:border-gray-400">キャンセル</Link>
          <button onClick={handleSave} disabled={saving || (!bulkMode && !form.keyword) || (bulkMode && !bulkText.trim())}
            className="flex-1 bg-purple-600 hover:bg-purple-700 disabled:opacity-40 text-white py-2.5 rounded-lg text-sm font-medium">
            {saving ? "保存中..." : "保存する"}
          </button>
        </div>
      </div>
    </div>
  );
}
