/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
export default function CategoryLoading() {
  return (
    <main className="max-w-6xl mx-auto px-4 py-8">
      <div className="flex gap-2 mb-6">
        {[12, 8, 24].map((w, i) => (
          <div key={i} className="flex gap-2 items-center">
            <div className={`h-4 w-${w} bg-gray-200 rounded animate-pulse`} />
            {i < 2 && <span className="text-gray-300">›</span>}
          </div>
        ))}
      </div>
      <div className="h-10 w-48 bg-gray-200 rounded animate-pulse mb-8" />
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
        {Array.from({ length: 9 }).map((_, i) => (
          <div key={i} className="bg-white border border-gray-100 rounded-xl overflow-hidden">
            <div className="h-36 bg-gradient-to-br from-purple-100 to-indigo-100 animate-pulse" />
            <div className="p-4 space-y-2">
              <div className="h-4 w-full bg-gray-200 rounded animate-pulse" />
              <div className="h-4 w-5/6 bg-gray-200 rounded animate-pulse" />
              <div className="h-3 w-full bg-gray-100 rounded animate-pulse" />
              <div className="h-3 w-3/4 bg-gray-100 rounded animate-pulse" />
            </div>
          </div>
        ))}
      </div>
    </main>
  );
}
