/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI v2056.8
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * Redistribution / derivative-work / reverse-engineering prohibited
 * (著作権法 / 不正競争防止法 / 当社利用規約 第 8 条).
 * License inquiries: nomura.y@soloptilink.com
 * ----------------------------------------------------------------*/
export default function Loading() {
  return (
    <main className="mx-auto max-w-[1240px] animate-pulse px-5 pt-12 md:px-6" aria-busy="true" aria-label="読み込み中">
      <div className="h-8 w-48 bg-paper-deep" />
      <div className="mt-12 grid gap-x-8 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">
        {Array.from({ length: 6 }).map((_, i) => (
          <div key={i}>
            <div className="aspect-[3/2] bg-paper-deep" />
            <div className="mt-4 h-3 w-20 bg-paper-deep" />
            <div className="mt-3 h-5 w-full bg-paper-deep" />
            <div className="mt-2 h-5 w-2/3 bg-paper-deep" />
          </div>
        ))}
      </div>
    </main>
  );
}
