/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
import { notFound } from "next/navigation";
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { formatDate } from "@/lib/utils";
import type { Metadata } from "next";

export const revalidate = 300;

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const cat = await prisma.category.findUnique({ where: { slug } });
  if (!cat) return { title: "カテゴリが見つかりません" };
  return { title: `${cat.name} | AI活用ラボ`, description: cat.description || undefined };
}

export default async function CategoryPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const category = await prisma.category.findUnique({ where: { slug } });
  if (!category) notFound();

  const articles = await prisma.article.findMany({
    where: { status: "published", categoryId: category.id },
    include: { _count: { select: { views: true } } },
    orderBy: { publishedAt: "desc" },
    take: 30,
  });

  return (
    <main className="max-w-5xl mx-auto px-4 py-10">
      <div className="mb-8">
        <Link href="/" className="text-sm text-gray-400 hover:text-gray-600">← ホーム</Link>
        <h1 className="text-2xl font-bold text-gray-900 mt-2">{category.name}</h1>
        {category.description && <p className="text-gray-500 mt-1">{category.description}</p>}
        <p className="text-sm text-gray-400 mt-1">{articles.length}件の記事</p>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {articles.map((article: any) => (
          <Link key={article.id} href={`/articles/${article.slug}`}
            className="flex gap-3 bg-white rounded-xl border border-gray-100 p-4 hover:shadow-md transition-shadow group">
            <div className="w-16 h-16 flex-shrink-0 bg-gradient-to-br from-purple-100 to-indigo-100 rounded-lg flex items-center justify-center text-2xl">🤖</div>
            <div className="flex-1 min-w-0">
              <h2 className="font-bold text-gray-900 group-hover:text-purple-600 transition-colors line-clamp-2 text-sm">{article.title}</h2>
              <div className="flex items-center gap-3 mt-2">
                <span className="text-xs text-gray-400">{formatDate(article.publishedAt || article.createdAt)}</span>
                <span className="text-xs text-gray-400">👁 {(article._count?.views||0).toLocaleString()}</span>
              </div>
            </div>
          </Link>
        ))}
        {articles.length === 0 && <p className="col-span-2 text-center py-20 text-gray-400">このカテゴリの記事を準備中です</p>}
      </div>
    </main>
  );
}
