/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI v2056.8
 * (c) 2026 SoloptiLink Inc. - All rights reserved.
 * Redistribution / derivative-work / reverse-engineering prohibited
 * (著作権法 / 不正競争防止法 / 当社利用規約 第 8 条).
 * License inquiries: nomura.y@soloptilink.com
 * ----------------------------------------------------------------*/
import { notFound } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
import { prisma } from "@/lib/prisma";
import ArticleCard, { type CardArticle } from "@/components/media/ArticleCard";
import { CATEGORIES, SITE_NAME, SITE_URL, categoryCover, categoryMeta } from "@/lib/media";

export const revalidate = 3600;
export const dynamicParams = true;

export async function generateStaticParams() {
  const categories = await prisma.category.findMany({ select: { slug: true } });
  return categories.map((c) => ({ slug: c.slug }));
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const cat = await prisma.category.findUnique({ where: { slug } });
  if (!cat) return { title: "カテゴリが見つかりません" };
  const name = categoryMeta(slug)?.name ?? cat.name;
  const desc = categoryMeta(slug)?.lead ?? cat.description ?? `${name}に関する記事一覧`;
  return {
    title: `${name}の記事一覧`,
    description: desc,
    alternates: { canonical: `${SITE_URL}/category/${slug}` },
    openGraph: { title: `${name}の記事一覧 | ${SITE_NAME}`, description: desc, url: `${SITE_URL}/category/${slug}`, siteName: SITE_NAME, locale: "ja_JP", type: "website", images: [{ url: categoryCover(slug) }] },
  };
}

export default async function CategoryPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const category = await prisma.category.findUnique({ where: { slug } });
  if (!category) notFound();
  const meta = categoryMeta(slug);

  const articles = (await prisma.article.findMany({
    where: { status: "published", categoryId: category.id },
    select: { id: true, slug: true, title: true, excerpt: true, publishedAt: true, createdAt: true, readingTime: true, category: { select: { slug: true, name: true } } },
    orderBy: { publishedAt: "desc" },
    take: 60,
  })) as CardArticle[];

  const [first, second, ...rest] = articles;
  const breadcrumbJsonLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "ホーム", item: SITE_URL },
      { "@type": "ListItem", position: 2, name: meta?.name ?? category.name, item: `${SITE_URL}/category/${slug}` },
    ],
  };

  return (
    <main>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }} />
      <section className="relative overflow-hidden bg-ink">
        <Image src={categoryCover(slug)} alt="" fill preload sizes="100vw" className="object-cover opacity-40" />
        <div className="absolute inset-0 bg-gradient-to-r from-black/80 via-black/50 to-black/10" />
        <div className="relative mx-auto max-w-[1240px] px-5 py-16 md:px-6 md:py-24">
          <nav aria-label="パンくずリスト" className="flex gap-2 text-[12px] text-white/80">
            <Link href="/" className="hover:text-white">ホーム</Link>
            <span aria-hidden>/</span>
            <span>カテゴリ</span>
          </nav>
          <p className="kicker mt-6 text-white/80">{meta?.en ?? "Category"}</p>
          <h1 className="mt-2 text-[32px] font-black tracking-[0.04em] text-white md:text-[48px]">{meta?.name ?? category.name}</h1>
          <p className="mt-4 max-w-xl text-[15px] leading-[1.9] text-white/80">{meta?.lead ?? category.description}</p>
          <p className="mt-6 text-[12px] text-white/80">{articles.length}本の記事</p>
        </div>
      </section>

      <nav aria-label="ほかのカテゴリ" className="border-b border-line">
        <div className="mx-auto flex max-w-[1240px] gap-1 overflow-x-auto px-5 md:px-6">
          {CATEGORIES.map((c) => (
            <Link
              key={c.slug}
              href={`/category/${c.slug}`}
              aria-current={c.slug === slug ? "page" : undefined}
              className={`shrink-0 border-b-2 px-3 py-4 text-[13px] font-bold ${c.slug === slug ? "border-accent text-ink" : "border-transparent text-mute hover:text-ink"}`}
            >
              {c.name}
            </Link>
          ))}
        </div>
      </nav>

      {articles.length === 0 ? (
        <p className="py-32 text-center text-mute">このカテゴリの記事はまだありません。</p>
      ) : (
        <div className="mx-auto max-w-[1240px] px-5 pt-12 md:px-6">
          <div className="grid gap-10 lg:grid-cols-2 lg:gap-12">
            {first && <ArticleCard a={first} variant="lead" sizes="(min-width: 1024px) 600px, 100vw" />}
            {second && <ArticleCard a={second} variant="lead" sizes="(min-width: 1024px) 600px, 100vw" />}
          </div>
          {rest.length > 0 && (
            <div className="mt-16 grid gap-x-8 gap-y-12 border-t border-line pt-12 sm:grid-cols-2 lg:grid-cols-3">
              {rest.map((a) => (
                <ArticleCard key={a.id} a={a} />
              ))}
            </div>
          )}
        </div>
      )}
    </main>
  );
}
