/* ----------------------------------------------------------------
 * Generated by SoloptiLinkAI BOOST  (c) 2026 SoloptiLink Inc.
 * ----------------------------------------------------------------*/
"use client";
import { useEffect, useState } from "react";

export default function AffiliatesPage() {
  const [products, setProducts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ name:"", url:"", commission:"", category:"AIサービス", description:"" });
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    fetch("/api/affiliates").then(r => r.json()).then(d => { setProducts(d); setLoading(false); });
  }, []);

  async function handleAdd() {
    setSaving(true);
    const res = await fetch("/api/affiliates", { method:"POST", headers:{"Content-Type":"application/json"}, body: JSON.stringify(form) });
    const p = await res.json();
    setProducts(prev => [p, ...prev]);
    setShowForm(false);
    setForm({ name:"", url:"", commission:"", category:"AIサービス", description:"" });
    setSaving(false);
  }

  const totalClicks = products.reduce((sum, p) => sum + (p.clickCount || 0), 0);

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">💰 アフィリエイト管理</h1>
          <p className="text-sm text-gray-500">総クリック数: {totalClicks.toLocaleString()}</p>
        </div>
        <button onClick={() => setShowForm(s => !s)} className="bg-purple-600 hover:bg-purple-700 text-white text-sm px-4 py-2 rounded-lg font-medium">
          + 商品追加
        </button>
      </div>

      {showForm && (
        <div className="bg-white rounded-xl border border-gray-100 p-5 space-y-4">
          <h2 className="font-semibold text-gray-800">新しいアフィリエイト商品</h2>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">商品名</label>
              <input value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))} className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none" />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">URL</label>
              <input value={form.url} onChange={e=>setForm(f=>({...f,url:e.target.value}))} className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none" />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">報酬率</label>
              <input value={form.commission} onChange={e=>setForm(f=>({...f,commission:e.target.value}))} className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none" placeholder="例: 30% / 月次報酬" />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">カテゴリ</label>
              <input value={form.category} onChange={e=>setForm(f=>({...f,category:e.target.value}))} className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none" />
            </div>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">説明</label>
            <input value={form.description} onChange={e=>setForm(f=>({...f,description:e.target.value}))} className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none" />
          </div>
          <div className="flex gap-3">
            <button onClick={() => setShowForm(false)} className="flex-1 border border-gray-300 text-gray-600 py-2 rounded-lg text-sm">キャンセル</button>
            <button onClick={handleAdd} disabled={saving||!form.name} className="flex-1 bg-purple-600 hover:bg-purple-700 disabled:opacity-40 text-white py-2 rounded-lg text-sm font-medium">
              {saving?"保存中...":"追加する"}
            </button>
          </div>
        </div>
      )}

      <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
        {loading ? (
          [...Array(6)].map((_,i) => <div key={i} className="h-36 bg-gray-200 rounded-xl animate-pulse" />)
        ) : products.map(p => (
          <div key={p.id} className={`bg-white rounded-xl border p-4 ${p.isActive ? "border-gray-100" : "border-gray-100 opacity-60"}`}>
            <div className="flex items-start justify-between mb-2">
              <div>
                <h3 className="font-semibold text-gray-800 text-sm">{p.name}</h3>
                <span className="text-xs text-gray-400">{p.category}</span>
              </div>
              <span className="text-xs bg-emerald-100 text-emerald-700 px-2 py-0.5 rounded-full font-medium">{p.commission}</span>
            </div>
            {p.description && <p className="text-xs text-gray-500 mb-3 line-clamp-2">{p.description}</p>}
            <div className="flex items-center justify-between">
              <span className="text-xs text-gray-400">クリック: <strong className="text-gray-700">{p.clickCount.toLocaleString()}</strong></span>
              <a href={p.url} target="_blank" rel="noopener noreferrer" className="text-xs text-purple-600 hover:underline">リンク確認 →</a>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
